// =============================================================================
//  PLAN COMÚN — Ciencias Naturales
//  Archivo: js/curricula/plan-comun/ciencias.js
//
//  Fuente: Bases Curriculares Mineduc (DS 439/2012 Básica, DS 369/2015 7°B–2°M,
//          DS 193/2019 3°M–4°M FG).
//
//  Estructura:
//    window.CURRICULA_PLAN_COMUN['ciencias'] = {
//      nombre, sigla, tramo, niveles,
//      oas: { '1B': [ { codigo, eje, descripcion }, ... ], ... },
//      actitudes: [...],      // específicas de la asignatura (o heredadas de _comun)
//      habilidades: [...],    // ejes de habilidades de la asignatura
//      unidades: { '1B': [...] }  // opcional — a completar en Fase B
//    }
// =============================================================================

window.CURRICULA_PLAN_COMUN = window.CURRICULA_PLAN_COMUN || {};

CURRICULA_PLAN_COMUN['ciencias'] = {
  nombre: 'Ciencias Naturales',
  sigla:  'CN',
  niveles: ['1B','2B','3B','4B','5B','6B','7B','8B','1M','2M'],
  // Ejes: Ciencias de la Vida · Ciencias Físicas y Químicas · Ciencias de la Tierra y el Universo
  oas: {
    '1B': [
      { codigo: 'OA1',  eje: 'Ciencias de la Vida',                   descripcion: 'Reconocer y observar, por medio de la exploración, que los seres vivos crecen, responden a estímulos del medio, se reproducen y necesitan agua, alimento y aire para vivir, comparándolos con las cosas no vivas.' },
      { codigo: 'OA2',  eje: 'Ciencias de la Vida',                   descripcion: 'Identificar y describir la ubicación y la función de los sentidos, proponiendo medidas para proteger y cuidar los órganos de los sentidos.' },
      { codigo: 'OA3',  eje: 'Ciencias de la Vida',                   descripcion: 'Observar e identificar, por medio de la exploración, las estructuras principales de las plantas: hojas, flores, tallos y raíces.' },
      { codigo: 'OA4',  eje: 'Ciencias de la Vida',                   descripcion: 'Observar y comparar animales de acuerdo a características como tamaño, cubierta corporal, estructuras de desplazamiento y tipo de desplazamiento, entre otras.' },
      { codigo: 'OA5',  eje: 'Ciencias de la Vida',                   descripcion: 'Identificar la ubicación y explicar la función de algunas partes del cuerpo que son fundamentales para vivir: corazón, pulmones, estómago, esqueleto y músculos.' },
      { codigo: 'OA6',  eje: 'Ciencias de la Vida',                   descripcion: 'Identificar, describir y comunicar hábitos de vida saludable para mantener el cuerpo sano y prevenir enfermedades (actividad física, aseo del cuerpo, lavado de alimentos, alimentación saludable, entre otros).' },
      { codigo: 'OA7',  eje: 'Ciencias Físicas y Químicas',           descripcion: 'Describir el tiempo atmosférico identificando instrumentos y marcadores como el viento, la temperatura y la precipitación.' },
      { codigo: 'OA8',  eje: 'Ciencias de la Tierra y el Universo',   descripcion: 'Describir características de las estaciones del año y sus efectos sobre los seres vivos (animales y plantas) y el ambiente.' },
      { codigo: 'OA9',  eje: 'Ciencias de la Tierra y el Universo',   descripcion: 'Relacionar las principales características (forma, tamaño, distancia, entre otras) del Sol, la Tierra y la Luna con algunos fenómenos como los días y las noches, las sombras o las estaciones del año.' },
      { codigo: 'OA10', eje: 'Ciencias Físicas y Químicas',           descripcion: 'Observar, describir y clasificar los cambios que experimenta el agua al ser expuesta al frío y al calor, a partir de experimentos simples.' },
      { codigo: 'OA11', eje: 'Ciencias de la Tierra y el Universo',   descripcion: 'Describir, dar ejemplos y practicar acciones cotidianas que contribuyen a cuidar el medioambiente, como apagar las luces, cerrar la llave del agua, reciclar y reutilizar.' }
    ],
    '2B': [
      { codigo: 'OA1',  eje: 'Ciencias de la Vida',                   descripcion: 'Observar y comparar las características de las etapas del ciclo de vida de distintos animales (mamíferos, aves, insectos y anfibios), relacionando con su hábitat.' },
      { codigo: 'OA2',  eje: 'Ciencias de la Vida',                   descripcion: 'Observar y comparar las características y necesidades de las plantas (luz, agua, dióxido de carbono y minerales), reconociendo su importancia para el ser humano.' },
      { codigo: 'OA3',  eje: 'Ciencias de la Vida',                   descripcion: 'Observar y distinguir, por medio de la exploración, las partes de una planta y las características de sus hojas, como forma, borde y tamaño, comparándolas.' },
      { codigo: 'OA4',  eje: 'Ciencias de la Vida',                   descripcion: 'Explicar la importancia de los animales, las plantas y el agua para los seres humanos, y proponer medidas para su cuidado.' },
      { codigo: 'OA5',  eje: 'Ciencias de la Vida',                   descripcion: 'Identificar la ubicación y explicar la función de los sentidos, proponiendo medidas para cuidarlos y para prevenir situaciones de riesgo.' },
      { codigo: 'OA6',  eje: 'Ciencias de la Vida',                   descripcion: 'Identificar y describir acciones para mantener una buena salud física y mental, como una alimentación adecuada, higiene personal, ejercicio físico, descanso y recreación.' },
      { codigo: 'OA7',  eje: 'Ciencias Físicas y Químicas',           descripcion: 'Describir y registrar el ciclo diario y las diferencias entre el día y la noche, a partir de la observación del Sol, la Luna, las estrellas y la luminosidad del cielo, entre otras, y reconocer los beneficios de la luz solar.' },
      { codigo: 'OA8',  eje: 'Ciencias Físicas y Químicas',           descripcion: 'Distinguir objetos tecnológicos que aportan beneficios a las personas y proteger el ambiente.' },
      { codigo: 'OA9',  eje: 'Ciencias de la Tierra y el Universo',   descripcion: 'Describir las características de algunos de los componentes del sistema solar (Sol, planetas, lunas, cometas y asteroides) en relación con su tamaño y localización.' },
      { codigo: 'OA10', eje: 'Ciencias de la Tierra y el Universo',   descripcion: 'Describir las principales características del paisaje costero, de los ríos y lagos, distinguiendo sus componentes y reconociendo acciones humanas que los afectan.' },
      { codigo: 'OA11', eje: 'Ciencias de la Tierra y el Universo',   descripcion: 'Identificar y comunicar los efectos de las actividades humanas sobre los paisajes y proponer medidas para el cuidado del entorno (reducir, reutilizar y reciclar).' }
    ],
    '3B': [
      { codigo: 'OA1',  eje: 'Ciencias de la Vida',                   descripcion: 'Reconocer y explicar que los seres vivos están formados por una o más células y que estas se organizan en tejidos, órganos y sistemas.' },
      { codigo: 'OA2',  eje: 'Ciencias de la Vida',                   descripcion: 'Observar y comparar las principales características de los vertebrados (mamíferos, aves, reptiles, anfibios y peces), ejemplificando para cada grupo.' },
      { codigo: 'OA3',  eje: 'Ciencias de la Vida',                   descripcion: 'Observar y clasificar los invertebrados (insectos, arácnidos, crustáceos, moluscos, entre otros) y distinguir características comunes y diferentes.' },
      { codigo: 'OA4',  eje: 'Ciencias de la Vida',                   descripcion: 'Reconocer y comparar diversos hábitats de los animales (polar, marino, desértico, entre otros) y las principales características y adaptaciones que les permiten vivir en ellos.' },
      { codigo: 'OA5',  eje: 'Ciencias de la Vida',                   descripcion: 'Reconocer, observar y distinguir cadenas alimentarias simples, identificando productores, consumidores y descomponedores en ecosistemas terrestres y acuáticos.' },
      { codigo: 'OA6',  eje: 'Ciencias de la Vida',                   descripcion: 'Explicar la importancia de los alimentos para el crecimiento y desarrollo de los seres humanos, identificando alimentos saludables y no saludables.' },
      { codigo: 'OA7',  eje: 'Ciencias de la Vida',                   descripcion: 'Observar, describir y clasificar las semillas y los frutos de diferentes plantas, así como la forma en que se dispersan.' },
      { codigo: 'OA8',  eje: 'Ciencias Físicas y Químicas',           descripcion: 'Identificar y describir las propiedades de la luz (viaja en línea recta, produce sombras, puede reflejarse), a partir de experiencias simples.' },
      { codigo: 'OA9',  eje: 'Ciencias Físicas y Químicas',           descripcion: 'Investigar, en forma experimental, los materiales que permiten el paso de la luz (transparentes, translúcidos y opacos), clasificándolos según su comportamiento.' },
      { codigo: 'OA10', eje: 'Ciencias Físicas y Químicas',           descripcion: 'Identificar los sonidos del entorno, describiendo sus diferencias (fuerte, suave, agudo, grave) y reconociendo fuentes sonoras naturales y artificiales.' },
      { codigo: 'OA11', eje: 'Ciencias de la Tierra y el Universo',   descripcion: 'Describir las características del suelo (retención de agua, presencia de arena, tierra y rocas) y explicar su importancia para los seres vivos.' },
      { codigo: 'OA12', eje: 'Ciencias de la Tierra y el Universo',   descripcion: 'Reconocer los cambios experimentados por el agua en el ciclo del agua, considerando estados físicos y la acción del Sol y del viento.' }
    ],
    '4B': [
      { codigo: 'OA1',  eje: 'Ciencias de la Vida',                   descripcion: 'Reconocer y explicar que los seres vivos están formados por una o más células, y que estas se agrupan formando tejidos, órganos y sistemas que cumplen funciones especializadas.' },
      { codigo: 'OA2',  eje: 'Ciencias de la Vida',                   descripcion: 'Observar y comparar ciclos de vida de plantas con flor y sin flor (musgos y helechos), y describir las etapas de germinación, crecimiento, reproducción, formación de flor y fruto y dispersión de la semilla.' },
      { codigo: 'OA3',  eje: 'Ciencias de la Vida',                   descripcion: 'Reconocer y explicar el rol de las plantas en la cadena alimentaria, identificando productores, consumidores y descomponedores, y el flujo de energía.' },
      { codigo: 'OA4',  eje: 'Ciencias de la Vida',                   descripcion: 'Analizar el efecto de la actividad humana sobre las plantas y animales, proponiendo medidas para su protección y mejor convivencia.' },
      { codigo: 'OA5',  eje: 'Ciencias de la Vida',                   descripcion: 'Identificar la ubicación y explicar la función de algunas partes del cuerpo humano (huesos, músculos, corazón, pulmones) y asociarlas a sus funciones.' },
      { codigo: 'OA6',  eje: 'Ciencias de la Vida',                   descripcion: 'Describir la importancia de una alimentación balanceada, equilibrada y saludable para el adecuado funcionamiento del cuerpo y el buen estado de salud.' },
      { codigo: 'OA7',  eje: 'Ciencias Físicas y Químicas',           descripcion: 'Identificar y describir las propiedades de la materia y los cambios físicos que experimenta (cambios de estado) a partir de experiencias.' },
      { codigo: 'OA8',  eje: 'Ciencias Físicas y Químicas',           descripcion: 'Medir y registrar la temperatura, la masa y el volumen de la materia utilizando instrumentos adecuados.' },
      { codigo: 'OA9',  eje: 'Ciencias Físicas y Químicas',           descripcion: 'Explicar el movimiento de los objetos en términos de distancia, tiempo y rapidez, utilizando un instrumento simple (cronómetro, cinta métrica).' },
      { codigo: 'OA10', eje: 'Ciencias de la Tierra y el Universo',   descripcion: 'Describir las características de la litósfera, hidrósfera y atmósfera, y los componentes de cada una, reconociendo sus interacciones.' },
      { codigo: 'OA11', eje: 'Ciencias de la Tierra y el Universo',   descripcion: 'Describir los efectos benéficos y perjudiciales del Sol sobre los seres vivos y el medioambiente, y algunas medidas de protección ante la sobreexposición solar.' },
      { codigo: 'OA12', eje: 'Ciencias de la Tierra y el Universo',   descripcion: 'Explicar los efectos de las catástrofes naturales (terremotos, maremotos, volcanismo, inundaciones, sequías) sobre las personas y el medioambiente, y comunicar medidas de prevención y seguridad.' }
    ],
    '5B': [
      { codigo: 'OA1',  eje: 'Ciencias de la Vida',                   descripcion: 'Reconocer y explicar que los seres vivos están formados por una o más células y que estas se organizan en tejidos, órganos y sistemas con funciones especializadas.' },
      { codigo: 'OA2',  eje: 'Ciencias de la Vida',                   descripcion: 'Identificar y describir por medio de modelos las estructuras básicas del sistema nervioso (encéfalo, médula espinal y nervios) y sus funciones, asociándolas a la coordinación del organismo.' },
      { codigo: 'OA3',  eje: 'Ciencias de la Vida',                   descripcion: 'Explicar la importancia de los hábitos saludables (alimentación balanceada, ejercicio físico, descanso, higiene) para mantener el buen funcionamiento del cuerpo y prevenir enfermedades.' },
      { codigo: 'OA4',  eje: 'Ciencias de la Vida',                   descripcion: 'Analizar el consumo de algunas drogas y los efectos nocivos para el organismo, destacando las formas de prevención y protección.' },
      { codigo: 'OA5',  eje: 'Ciencias de la Vida',                   descripcion: 'Analizar, comparar y clasificar los ecosistemas chilenos, identificando componentes bióticos y abióticos, factores que inciden en su equilibrio y amenazas por acción humana.' },
      { codigo: 'OA6',  eje: 'Ciencias de la Vida',                   descripcion: 'Investigar y reportar sobre los efectos de las actividades humanas en los ecosistemas, proponiendo acciones para su conservación y la recuperación.' },
      { codigo: 'OA7',  eje: 'Ciencias Físicas y Químicas',           descripcion: 'Identificar y describir las propiedades de la materia (masa, volumen, densidad) y los cambios físicos y químicos, distinguiéndolos a partir de experiencias sencillas.' },
      { codigo: 'OA8',  eje: 'Ciencias Físicas y Químicas',           descripcion: 'Explicar, por medio de modelos, que la materia está formada por partículas (átomos y moléculas) en movimiento y con distinto grado de cohesión en los estados sólido, líquido y gaseoso.' },
      { codigo: 'OA9',  eje: 'Ciencias Físicas y Químicas',           descripcion: 'Identificar y describir las propiedades de las mezclas homogéneas y heterogéneas, y algunos métodos simples de separación (filtración, decantación, evaporación, tamizado).' },
      { codigo: 'OA10', eje: 'Ciencias de la Tierra y el Universo',   descripcion: 'Describir el movimiento del Sistema Solar (Sol y planetas) y los efectos de la traslación y rotación de la Tierra en la sucesión de días y noches y en las estaciones del año.' },
      { codigo: 'OA11', eje: 'Ciencias de la Tierra y el Universo',   descripcion: 'Describir las características de los eclipses, fases de la Luna y mareas, y relacionarlos con los movimientos del Sistema Sol–Tierra–Luna.' }
    ],
    '6B': [
      { codigo: 'OA1',  eje: 'Ciencias de la Vida',                   descripcion: 'Identificar y describir la función de los principales componentes de los sistemas respiratorio, circulatorio, digestivo y excretor del cuerpo humano, reconociendo su interrelación.' },
      { codigo: 'OA2',  eje: 'Ciencias de la Vida',                   descripcion: 'Explicar los cambios que experimenta el cuerpo humano durante la pubertad (cambios físicos, psicológicos, sociales, diferencias entre hombres y mujeres) y su importancia en el desarrollo integral de la persona.' },
      { codigo: 'OA3',  eje: 'Ciencias de la Vida',                   descripcion: 'Reconocer y explicar la función de los órganos del sistema reproductor femenino y masculino, y asociarlos con los procesos de la reproducción humana.' },
      { codigo: 'OA4',  eje: 'Ciencias de la Vida',                   descripcion: 'Investigar, experimental y bibliográficamente, los efectos nocivos del consumo de tabaco y alcohol en el organismo, proponiendo medidas de prevención y autocuidado.' },
      { codigo: 'OA5',  eje: 'Ciencias de la Vida',                   descripcion: 'Analizar e investigar los efectos de la actividad humana sobre los ecosistemas (deforestación, contaminación, incendios, caza), proponiendo acciones para su conservación y sustentabilidad.' },
      { codigo: 'OA6',  eje: 'Ciencias Físicas y Químicas',           descripcion: 'Identificar y describir las propiedades y transformaciones de la energía (cinética, potencial, térmica, lumínica, eléctrica, sonora), y algunos ejemplos de su transformación en el entorno cotidiano.' },
      { codigo: 'OA7',  eje: 'Ciencias Físicas y Químicas',           descripcion: 'Explicar algunas formas de generación y transmisión de electricidad y describir circuitos eléctricos simples, usando materiales conductores y aislantes, y representarlos mediante modelos.' },
      { codigo: 'OA8',  eje: 'Ciencias Físicas y Químicas',           descripcion: 'Investigar, experimentalmente, la forma en que se transfiere el calor entre los materiales (conducción, convección, radiación), distinguiendo conductores y aislantes térmicos.' },
      { codigo: 'OA9',  eje: 'Ciencias de la Tierra y el Universo',   descripcion: 'Explicar, con base en evidencia, que los suelos presentan características y propiedades distintas (color, retención de agua, permeabilidad, capacidad de producción), y que estas inciden en la vida de los organismos.' },
      { codigo: 'OA10', eje: 'Ciencias de la Tierra y el Universo',   descripcion: 'Investigar y describir los principales recursos naturales de Chile, su uso y los efectos de la actividad humana en su disponibilidad, y proponer formas de uso responsable.' }
    ],
    '7B': [
      { codigo: 'OA1',  eje: 'Ciencias de la Vida (Biología)',        descripcion: 'Explicar, por medio de modelos, la organización estructural y funcional de los seres vivos desde la célula hasta sistemas de órganos, reconociendo los niveles de organización biológica.' },
      { codigo: 'OA2',  eje: 'Ciencias de la Vida (Biología)',        descripcion: 'Describir, por medio de modelos, la estructura y función de los sistemas digestivo, respiratorio y circulatorio del cuerpo humano, y explicar su interrelación.' },
      { codigo: 'OA3',  eje: 'Ciencias de la Vida (Biología)',        descripcion: 'Investigar y explicar los efectos nocivos del consumo excesivo de alcohol, tabaco y otras sustancias en los sistemas respiratorio, circulatorio y nervioso, y proponer medidas de prevención.' },
      { codigo: 'OA4',  eje: 'Ciencias de la Vida (Biología)',        descripcion: 'Explicar la importancia de la actividad física y una alimentación saludable para prevenir enfermedades cardiovasculares, respiratorias y metabólicas.' },
      { codigo: 'OA5',  eje: 'Ciencias de la Vida (Biología)',        descripcion: 'Investigar y analizar las funciones, la ubicación y las estructuras del sistema reproductor humano (femenino y masculino) y explicar el ciclo menstrual, la fecundación y el desarrollo embrionario.' },
      { codigo: 'OA6',  eje: 'Ciencias Físicas (Física)',             descripcion: 'Explicar que las ondas transportan energía sin transportar materia, distinguiendo los tipos de ondas (transversales y longitudinales), sus propiedades (amplitud, frecuencia, longitud de onda, rapidez) y su relación con el sonido.' },
      { codigo: 'OA7',  eje: 'Ciencias Físicas (Física)',             descripcion: 'Describir y aplicar los principios básicos de la óptica geométrica (reflexión y refracción) y explicar cómo se forman las imágenes en espejos planos y lentes simples.' },
      { codigo: 'OA8',  eje: 'Ciencias Químicas (Química)',           descripcion: 'Explicar la estructura y organización de la materia a partir del modelo atómico (protones, neutrones, electrones) y la tabla periódica (grupos, períodos, propiedades periódicas).' },
      { codigo: 'OA9',  eje: 'Ciencias Químicas (Química)',           descripcion: 'Investigar experimentalmente y explicar los enlaces químicos (iónico y covalente) y las fórmulas de compuestos químicos más comunes en la vida cotidiana (agua, sal, azúcar, dióxido de carbono).' },
      { codigo: 'OA10', eje: 'Ciencias de la Tierra y el Universo',   descripcion: 'Investigar y describir los principales procesos geológicos (tectónica de placas, formación de montañas, erupciones volcánicas, sismos) y explicar sus efectos en el territorio.' }
    ],
    '8B': [
      { codigo: 'OA1',  eje: 'Ciencias de la Vida (Biología)',        descripcion: 'Explicar, por medio de modelos, la organización e interacción de los componentes del sistema nervioso (central y periférico) y endocrino, y su rol en la homeostasis del organismo.' },
      { codigo: 'OA2',  eje: 'Ciencias de la Vida (Biología)',        descripcion: 'Investigar y explicar la estructura, función y modo de transmisión de distintos agentes infecciosos (virus, bacterias, hongos, parásitos), y las formas de prevención de enfermedades asociadas.' },
      { codigo: 'OA3',  eje: 'Ciencias de la Vida (Biología)',        descripcion: 'Explicar la teoría de la evolución y el concepto de selección natural, a partir de las evidencias fósiles, anatómicas y moleculares, y los aportes de Darwin.' },
      { codigo: 'OA4',  eje: 'Ciencias de la Vida (Biología)',        descripcion: 'Analizar y explicar cómo las acciones humanas afectan la biodiversidad y los ecosistemas, proponiendo acciones de conservación del patrimonio natural.' },
      { codigo: 'OA5',  eje: 'Ciencias Físicas (Física)',             descripcion: 'Analizar y aplicar los conceptos de fuerza y movimiento (leyes de Newton, fuerza de gravedad, fuerza normal, fuerza de roce), explicando fenómenos cotidianos.' },
      { codigo: 'OA6',  eje: 'Ciencias Físicas (Física)',             descripcion: 'Aplicar los conceptos de energía cinética y potencial, identificando transformaciones en distintos sistemas (mecánicos, térmicos, eléctricos) y la conservación de la energía.' },
      { codigo: 'OA7',  eje: 'Ciencias Químicas (Química)',           descripcion: 'Explicar las reacciones químicas (reactantes, productos, ley de conservación de la masa) y clasificarlas (síntesis, descomposición, sustitución, combustión), a partir de experimentos.' },
      { codigo: 'OA8',  eje: 'Ciencias Químicas (Química)',           descripcion: 'Explicar la formación y propiedades de soluciones químicas (disolución, soluto, solvente, concentración) y los factores que afectan la solubilidad y la rapidez de la disolución.' },
      { codigo: 'OA9',  eje: 'Ciencias de la Tierra y el Universo',   descripcion: 'Investigar y explicar las principales causas y efectos del cambio climático global, y proponer medidas de mitigación y adaptación a nivel personal, local y global.' },
      { codigo: 'OA10', eje: 'Ciencias de la Tierra y el Universo',   descripcion: 'Analizar y describir la estructura y evolución del universo (Big Bang, formación de galaxias, estrellas y sistemas planetarios), apoyándose en modelos y evidencia.' }
    ],
    // ── 1°M — Programa de Estudio Mineduc, DEx 1264/2016 (DS 369/2015) ──────
    //    20 OAs en 3 ejes: Biología (1-8), Física (9-16), Química (17-20).
    '1M': [
      { codigo: 'OA1',  eje: 'Biología', descripcion: 'Explicar, basándose en evidencias, que los fósiles: se forman a partir de restos de animales y plantas; se forman en rocas sedimentarias; se ubican de acuerdo a su antigüedad en los estratos de la Tierra.' },
      { codigo: 'OA2',  eje: 'Biología', descripcion: 'Analizar e interpretar datos para proveer de evidencias que apoyen que la diversidad de organismos es el resultado de la evolución, considerando: evidencias de la evolución (como el registro fósil, las estructuras anatómicas homólogas, la embriología y las secuencias de ADN); los postulados de la teoría de la selección natural; los aportes de científicos como Darwin y Wallace a las teorías evolutivas.' },
      { codigo: 'OA3',  eje: 'Biología', descripcion: 'Explicar, basándose en evidencias, que la clasificación de la diversidad de organismos se construye a través del tiempo sobre la base de criterios taxonómicos que permiten organizarlos en grupos y subgrupos, identificando sus relaciones de parentesco con ancestros comunes.' },
      { codigo: 'OA4',  eje: 'Biología', descripcion: 'Investigar y explicar cómo se organizan e interactúan los seres vivos en diversos ecosistemas, a partir de ejemplos de Chile, considerando: los niveles de organización de los seres vivos (como organismo, población, comunidad, ecosistema); las interacciones biológicas (como depredación, competencia, comensalismo, mutualismo, parasitismo).' },
      { codigo: 'OA5',  eje: 'Biología', descripcion: 'Analizar e interpretar los factores que afectan el tamaño de las poblaciones (propagación de enfermedades, disponibilidad de energía y de recursos alimentarios, sequías, entre otros) y predecir posibles consecuencias sobre el ecosistema.' },
      { codigo: 'OA6',  eje: 'Biología', descripcion: 'Desarrollar modelos que expliquen: el ciclo del carbono, el nitrógeno, el agua y el fósforo, y su importancia biológica; los flujos de energía en un ecosistema (redes y pirámides tróficas); la trayectoria de contaminantes y su bioacumulación.' },
      { codigo: 'OA7',  eje: 'Biología', descripcion: 'Explicar, por medio de una investigación, el rol de la fotosíntesis y la respiración celular en el ecosistema considerando: el flujo de la energía; el ciclo de la materia.' },
      { codigo: 'OA8',  eje: 'Biología', descripcion: 'Explicar y evaluar los efectos de acciones humanas (conservación ambiental, cultivos, forestación y deforestación, entre otras) y de fenómenos naturales (sequías, erupciones volcánicas, entre otras) en relación con: el equilibrio de los ecosistemas; la disponibilidad de recursos naturales renovables y no renovables; las posibles medidas para un desarrollo sustentable.' },
      { codigo: 'OA9',  eje: 'Física',   descripcion: 'Demostrar que comprende, por medio de la creación de modelos y experimentos, que las ondas transmiten energía y que se pueden reflejar, refractar y absorber, explicando y considerando: sus características (amplitud, frecuencia, longitud de onda y velocidad de propagación, entre otras); los criterios para clasificarlas (mecánicas, electromagnéticas, transversales, longitudinales, superficiales).' },
      { codigo: 'OA10', eje: 'Física',   descripcion: 'Explicar fenómenos del sonido perceptibles por las personas, como el eco, la resonancia y el efecto Doppler, entre otros, utilizando el modelo ondulatorio y por medio de la experimentación, considerando sus: características y cualidades (intensidad, tono, timbre y rapidez); emisiones (en cuerdas vocales, en parlantes e instrumentos musicales); consecuencias (contaminación y medio de comunicación); aplicaciones tecnológicas (ecógrafo, sonar y estetoscopio, entretención, entre otras).' },
      { codigo: 'OA11', eje: 'Física',   descripcion: 'Explicar fenómenos luminosos, como la reflexión, la refracción, la interferencia y el efecto Doppler, entre otros, por medio de la experimentación y el uso de modelos, considerando: los modelos corpuscular y ondulatorio de la luz; las características y la propagación de la luz (viaja en línea recta, formación de sombras y posee rapidez, entre otras); la formación de imágenes (espejos y lentes); la formación de colores (difracción, colores primarios y secundarios, filtros); sus aplicaciones tecnológicas (lentes, telescopio, prismáticos y focos, entre otros).' },
      { codigo: 'OA12', eje: 'Física',   descripcion: 'Explorar y describir el funcionamiento del oído y del ojo humano, considerando: la recepción de ondas sonoras y luminosas; el espectro sonoro y de la luz visible; sus capacidades, limitaciones y consecuencias sociales; la tecnología correctiva (lentes y audífonos).' },
      { codigo: 'OA13', eje: 'Física',   descripcion: 'Describir el origen y la propagación, por medio del modelo ondulatorio, de la energía liberada en un sismo, considerando: los parámetros que lo describen (epicentro, hipocentro, área de ruptura, magnitud e intensidad); los tipos de ondas sísmicas (primarias, secundarias y superficiales); su medición y registro (sismógrafo, escalas sísmicas); sus consecuencias directas e indirectas en la superficie de la Tierra (como tsunamis) y en la sociedad; su importancia en geología, por ejemplo, en el estudio de la estructura interna de la Tierra.' },
      { codigo: 'OA14', eje: 'Física',   descripcion: 'Crear modelos que expliquen los fenómenos astronómicos del sistema solar relacionados con: los movimientos del sistema Tierra-Luna y los fenómenos de luz y sombra, como las fases lunares y los eclipses; los movimientos de la Tierra respecto del Sol y sus consecuencias, como las estaciones climáticas; la comparación de los distintos planetas con la Tierra en cuanto a su distancia al Sol, su tamaño, su período orbital, su atmósfera y otros.' },
      { codigo: 'OA15', eje: 'Física',   descripcion: 'Describir y comparar diversas estructuras cósmicas, como meteoros, asteroides, cometas, satélites, planetas, estrellas, nebulosas, galaxias y cúmulo de galaxias, considerando: sus tamaños y formas; sus posiciones en el espacio; temperatura, masa, color y magnitud, entre otros.' },
      { codigo: 'OA16', eje: 'Física',   descripcion: 'Investigar y explicar sobre la investigación astronómica en Chile y el resto del mundo, considerando aspectos como: el clima y las ventajas que ofrece nuestro país para la observación astronómica; la tecnología utilizada (telescopios, radiotelescopios y otros instrumentos astronómicos); la información que proporciona la luz y otras radiaciones emitidas por los astros; los aportes de científicas chilenas y científicos chilenos.' },
      { codigo: 'OA17', eje: 'Química',  descripcion: 'Investigar experimentalmente y explicar, usando evidencias, que la fermentación, la combustión provocada por un motor y un calefactor, y la oxidación de metales, entre otras, son reacciones químicas presentes en la vida diaria, considerando: la producción de gas, la formación de precipitados, el cambio de temperatura, color y olor, y la emisión de luz, entre otros; la influencia de la cantidad de sustancia, la temperatura, el volumen y la presión en ellas; su representación simbólica en ecuaciones químicas; su impacto en los seres vivos y el entorno.' },
      { codigo: 'OA18', eje: 'Química',  descripcion: 'Desarrollar un modelo que describa cómo el número total de átomos no varía en una reacción química y cómo la masa se conserva aplicando la ley de la conservación de la materia.' },
      { codigo: 'OA19', eje: 'Química',  descripcion: 'Explicar la formación de compuestos binarios y ternarios, considerando las fuerzas eléctricas entre partículas y la nomenclatura inorgánica correspondiente.' },
      { codigo: 'OA20', eje: 'Química',  descripcion: 'Establecer relaciones cuantitativas entre reactantes y productos en reacciones químicas (estequiometría) y explicar la formación de compuestos útiles para los seres vivos, como la formación de la glucosa en la fotosíntesis.' }
    ],
    // ── 2°M — Programa de Estudio Mineduc, DEx 1264/2016 (DS 369/2015) ──────
    //    18 OAs en 3 ejes: Biología (1-8), Física (9-14), Química (15-18).
    '2M': [
      { codigo: 'OA1',  eje: 'Biología', descripcion: 'Explicar cómo el sistema nervioso coordina las acciones del organismo para adaptarse a estímulos del ambiente por medio de señales transmitidas por neuronas a lo largo del cuerpo, e investigar y comunicar sus cuidados, como las horas de sueño, el consumo de drogas, café y alcohol, y la prevención de traumatismos.' },
      { codigo: 'OA2',  eje: 'Biología', descripcion: 'Crear modelos que expliquen la regulación de: la glicemia por medio del control de las hormonas pancreáticas; los caracteres sexuales y las funciones reproductivas por medio del control de las hormonas sexuales en el organismo.' },
      { codigo: 'OA3',  eje: 'Biología', descripcion: 'Explicar que la sexualidad humana y la reproducción son aspectos fundamentales de la vida del ser humano, considerando los aspectos biológicos, sociales, afectivos y psicológicos, y la responsabilidad individual frente a sí mismo y los demás.' },
      { codigo: 'OA4',  eje: 'Biología', descripcion: 'Describir la fecundación, la implantación y el desarrollo del embrión, y analizar la responsabilidad de los padres en la nutrición prenatal y la lactancia.' },
      { codigo: 'OA5',  eje: 'Biología', descripcion: 'Explicar y evaluar los métodos de regulación de la fertilidad e identificar los elementos de una paternidad y una maternidad responsables.' },
      { codigo: 'OA6',  eje: 'Biología', descripcion: 'Investigar y argumentar, basándose en evidencias, que el material genético se transmite de generación en generación en organismos como plantas y animales, considerando: la comparación de la mitosis y la meiosis; las causas y consecuencias de anomalías y pérdida de control de la división celular (tumor, cáncer, trisomía, entre otros).' },
      { codigo: 'OA7',  eje: 'Biología', descripcion: 'Desarrollar una explicación científica, basada en evidencias, sobre los procesos de herencia genética en plantas y animales, aplicando los principios básicos de la herencia propuestos por Mendel.' },
      { codigo: 'OA8',  eje: 'Biología', descripcion: 'Investigar y explicar las aplicaciones que han surgido a raíz de la manipulación genética para generar alimentos, detergentes, vestuario, fármacos u otras, y evaluar sus implicancias éticas y sociales.' },
      { codigo: 'OA9',  eje: 'Física',   descripcion: 'Analizar, sobre la base de la experimentación, el movimiento rectilíneo uniforme y acelerado de un objeto respecto de un sistema de referencia espacio-temporal, considerando variables como la posición, la velocidad y la aceleración en situaciones cotidianas.' },
      { codigo: 'OA10', eje: 'Física',   descripcion: 'Explicar, por medio de investigaciones experimentales, los efectos que tiene una fuerza neta sobre un objeto, utilizando las leyes de Newton y el diagrama de cuerpo libre.' },
      { codigo: 'OA11', eje: 'Física',   descripcion: 'Describir el movimiento de un objeto, usando la ley de conservación de la energía mecánica y los conceptos de trabajo y potencia mecánica.' },
      { codigo: 'OA12', eje: 'Física',   descripcion: 'Analizar e interpretar datos de investigaciones sobre colisiones entre objetos, considerando: la cantidad de movimiento de un cuerpo en función del impulso que adquiere; la ley de conservación de cantidad de movimiento (momento lineal o momentum).' },
      { codigo: 'OA13', eje: 'Física',   descripcion: 'Demostrar que comprenden que el conocimiento del Universo cambia y aumenta a partir de nuevas evidencias, usando modelos como el geocéntrico y el heliocéntrico, y teorías como la del Big-Bang, entre otros.' },
      { codigo: 'OA14', eje: 'Física',   descripcion: 'Explicar cualitativamente por medio de las leyes de Kepler y la de gravitación universal de Newton: el origen de las mareas; la formación y dinámica de estructuras cósmicas naturales, como el sistema solar y sus componentes, las estrellas y las galaxias; el movimiento de estructuras artificiales como sondas, satélites y naves espaciales.' },
      { codigo: 'OA15', eje: 'Química',  descripcion: 'Explicar, por medio de modelos y la experimentación, las propiedades de las soluciones en ejemplos cercanos, considerando: el estado físico (sólido, líquido y gaseoso); sus componentes (soluto y solvente); la cantidad de soluto disuelto (concentración).' },
      { codigo: 'OA16', eje: 'Química',  descripcion: 'Planificar y conducir una investigación experimental para proveer evidencias que expliquen las propiedades coligativas de las soluciones y su importancia en procesos cotidianos (la mantención de frutas y mermeladas en conserva) e industriales (aditivos en el agua de radiadores).' },
      { codigo: 'OA17', eje: 'Química',  descripcion: 'Crear modelos del carbono y explicar sus propiedades como base para la formación de moléculas útiles para los seres vivos (biomoléculas presentes en la célula) y el entorno (hidrocarburos como petróleo y sus derivados).' },
      { codigo: 'OA18', eje: 'Química',  descripcion: 'Desarrollar modelos que expliquen la estereoquímica e isomería de compuestos orgánicos como la glucosa, identificando sus propiedades y su utilidad para los seres vivos.' }
    ]
  }
};

