// =============================================================================
//  PLAN COMÚN — Historia, Geografía y Ciencias Sociales
//  Archivo: js/curricula/plan-comun/historia.js
//
//  Fuente: Bases Curriculares Mineduc (DS 439/2012 Básica, DS 369/2015 7°B–2°M,
//          DS 193/2019 3°M–4°M FG).
//
//  Estructura:
//    window.CURRICULA_PLAN_COMUN['historia'] = {
//      nombre, sigla, tramo, niveles,
//      oas: { '1B': [ { codigo, eje, descripcion }, ... ], ... },
//      actitudes: [...],      // específicas de la asignatura (o heredadas de _comun)
//      habilidades: [...],    // ejes de habilidades de la asignatura
//      unidades: { '1B': [...] }  // opcional — a completar en Fase B
//    }
// =============================================================================

window.CURRICULA_PLAN_COMUN = window.CURRICULA_PLAN_COMUN || {};

CURRICULA_PLAN_COMUN['historia'] = {
  nombre: 'Historia, Geografía y Ciencias Sociales',
  sigla:  'HIS',
  niveles: ['1B','2B','3B','4B','5B','6B','7B','8B','1M','2M','3M','4M'],
  oas: {
    '1B': [
      { codigo: 'OA1',  eje: 'Historia',             descripcion: 'Nombrar y secuenciar días de la semana y meses del año, utilizando calendarios, e identificar el año en curso.' },
      { codigo: 'OA2',  eje: 'Historia',             descripcion: 'Secuenciar acontecimientos y actividades de la vida cotidiana, personal y familiar, utilizando categorías relativas de ubicación temporal como antes, después; ayer, hoy, mañana; día, noche; este año, el año pasado, el año próximo.' },
      { codigo: 'OA3',  eje: 'Historia',             descripcion: 'Registrar y comunicar información sobre elementos que forman parte de su identidad personal (nombre, fecha de nacimiento, lugar de procedencia, ascendencias, gustos, intereses, amigos y otros) para reconocer sus características individuales.' },
      { codigo: 'OA4',  eje: 'Historia',             descripcion: 'Obtener y comunicar aspectos de la historia de su familia y sus costumbres, como origen de sus antepasados, los lugares donde vivieron, hitos y tradiciones familiares, a través de relatos, fotografías y entrevistas a adultos, entre otros.' },
      { codigo: 'OA5',  eje: 'Historia',             descripcion: 'Reconocer diversas expresiones del patrimonio histórico de su entorno familiar y local, como costumbres, tradiciones, leyendas, canciones, construcciones, monumentos y lugares con significado local.' },
      { codigo: 'OA6',  eje: 'Historia',             descripcion: 'Reconocer los símbolos representativos de Chile (como la bandera, el escudo y el himno nacional), describir costumbres, actividades y la participación de hombres y mujeres respecto de conmemoraciones nacionales (Fiestas Patrias, Día del Descubrimiento de dos Mundos, Combate Naval de Iquique, entre otros) y reconocer en ellos un elemento de unidad e identidad nacional.' },
      { codigo: 'OA7',  eje: 'Historia',             descripcion: 'Conocer sobre la vida de hombres y mujeres que han contribuido a la sociedad chilena en diversos ámbitos; por ejemplo, fundadores de ciudades, exploradores, personas que han fundado o creado instituciones, deportistas, científicos, artistas y grandes poetas, entre otros.' },
      { codigo: 'OA8',  eje: 'Geografía',            descripcion: 'Reconocer que los mapas y planos son formas de representar lugares.' },
      { codigo: 'OA9',  eje: 'Geografía',            descripcion: 'Identificar a Chile en mapas, incluyendo la cordillera de los Andes, el océano Pacífico, su país y ciudad, la localidad donde vive, y Santiago, la capital.' },
      { codigo: 'OA10', eje: 'Geografía',            descripcion: 'Ubicar Chile, Santiago, la propia región y su capital en el globo terráqueo o en mapas, y describir características del entorno geográfico cercano, utilizando vocabulario geográfico adecuado (camino, pueblo, construcciones, cordillera, mar, vegetación y desierto, entre otros).' },
      { codigo: 'OA11', eje: 'Geografía',            descripcion: 'Conocer cómo viven otros niños en diferentes partes del mundo por medio de imágenes y relatos, ubicando en un globo terráqueo o mapamundi los países donde viven y comparándolos con la forma en que viven los niños en Chile.' },
      { codigo: 'OA12', eje: 'Geografía',            descripcion: 'Practicar y reconocer algunas normas de prevención de riesgos y cuidado de sí mismo (como normas de tránsito, de seguridad, en caso de desastres naturales) y de autocuidado (como no recibir regalos de desconocidos, rechazar todo tipo de agresiones y solicitar ayuda).' },
      { codigo: 'OA13', eje: 'Formación Ciudadana',  descripcion: 'Mantener una conducta honesta en la vida cotidiana, en los juegos y en el trabajo escolar, hablando con la verdad, respetando las reglas de los juegos sin hacer trampa, y reconociendo sus errores y sus acciones, entre otros.' },
      { codigo: 'OA14', eje: 'Formación Ciudadana',  descripcion: 'Explicar y aplicar algunas normas para la buena convivencia y para la seguridad de todos los miembros de la comunidad escolar que comparten actividades en los diversos ámbitos escolares (sala de clases, patio, actos cívicos, formaciones, entre otros).' },
      { codigo: 'OA15', eje: 'Formación Ciudadana',  descripcion: 'Identificar la labor que cumplen, en beneficio de la comunidad, instituciones como la escuela, la municipalidad, el hospital, Carabineros, bomberos y las personas que trabajan en ellas.' },
      { codigo: 'OA16', eje: 'Formación Ciudadana',  descripcion: 'Conocer, proponer, aplicar y explicar la importancia de algunas normas necesarias para cuidarse, cuidar a otros y evitar situaciones de riesgo (como seguridad vial, vulneración de intimidad, abuso sexual infantil, consumo de drogas, desastres naturales).' }
    ],
    '2B': [
      { codigo: 'OA1',  eje: 'Historia',             descripcion: 'Describir los modos de vida de algunos pueblos originarios de Chile en el período precolombino, incluyendo ubicación geográfica, medio natural, vida nómada o sedentaria, roles de hombres y mujeres, herramientas y tecnología, alimentación, costumbres, sistemas de creencias, idioma y expresiones artísticas.' },
      { codigo: 'OA2',  eje: 'Historia',             descripcion: 'Comparar el modo de vida y expresiones culturales de pueblos indígenas presentes en Chile actual (como aymara, mapuche, rapa nui) con los del período precolombino, identificando aspectos de su cultura que se han mantenido hasta el presente y aspectos que han cambiado.' },
      { codigo: 'OA3',  eje: 'Historia',             descripcion: 'Distinguir los diversos aportes a la sociedad chilena proveniente de los pueblos originarios (palabras, alimentos, tradiciones, cultura, entre otros) y de los españoles (idioma, religión, alimentos, cultura, arquitectura, entre otros), y reconocer nuestra sociedad como mestiza.' },
      { codigo: 'OA4',  eje: 'Historia',             descripcion: 'Obtener y comunicar aspectos de la historia de su comunidad, como costumbres, tradiciones, ritos, fiestas, leyendas, tradiciones orales y creencias de su localidad o región, mediante entrevistas, narraciones, visitas y otros.' },
      { codigo: 'OA5',  eje: 'Historia',             descripcion: 'Identificar y dar ejemplos de distintas expresiones del patrimonio cultural de Chile (como conjuntos arquitectónicos, barrios, sitios arqueológicos, artesanía, fiestas populares, música, comidas típicas).' },
      { codigo: 'OA6',  eje: 'Geografía',            descripcion: 'Leer y dibujar planos simples de su entorno, utilizando puntos de referencia, categorías de posición relativa y simbología pictórica.' },
      { codigo: 'OA7',  eje: 'Geografía',            descripcion: 'Ubicar Chile, Santiago, la propia región y su capital en el globo terráqueo o en mapas, y describir la ubicación relativa de países limítrofes y de otros países de América del Sur, utilizando los puntos cardinales.' },
      { codigo: 'OA8',  eje: 'Geografía',            descripcion: 'Clasificar y caracterizar algunos paisajes de Chile según su ubicación en la zona norte, centro y sur del país, observando imágenes, utilizando vocabulario geográfico adecuado (océano, río, cordillera de los Andes y de la Costa, desierto, valle, costa, volcán, archipiélago, lago, ventisquero, entre otros) e identificando recursos naturales presentes.' },
      { codigo: 'OA9',  eje: 'Geografía',            descripcion: 'Distinguir algunos rasgos principales de pueblos y culturas del mundo (lengua, religión, comida, costumbres, celebraciones, bailes) y reconocer que cada cual tiene su propia identidad cultural.' },
      { codigo: 'OA10', eje: 'Geografía',            descripcion: 'Reconocer diversas expresiones del patrimonio natural de Chile y de su región, como paisajes, flora y fauna característicos, y lugares de relevancia natural.' },
      { codigo: 'OA11', eje: 'Formación Ciudadana',  descripcion: 'Mantener una conducta honesta en la vida cotidiana, en los juegos y en el trabajo escolar, hablando con la verdad, respetando las reglas de los juegos sin hacer trampa, y reconociendo sus errores y sus acciones, entre otros.' },
      { codigo: 'OA12', eje: 'Formación Ciudadana',  descripcion: 'Explicar y aplicar algunas normas para la buena convivencia y para la seguridad de todos los miembros de la comunidad escolar, reconociendo su sentido y valor en el ámbito escolar (sala de clases, patio, actos cívicos, formaciones, entre otros).' },
      { codigo: 'OA13', eje: 'Formación Ciudadana',  descripcion: 'Identificar a las autoridades (presidente, alcalde, intendente, entre otros) y explicar algunas de sus labores principales y cómo contribuyen al bien común de la sociedad.' },
      { codigo: 'OA14', eje: 'Formación Ciudadana',  descripcion: 'Conocer, proponer y aplicar formas de resolución pacífica de conflictos, considerando la empatía hacia los otros, el diálogo y el autocuidado.' },
      { codigo: 'OA15', eje: 'Formación Ciudadana',  descripcion: 'Practicar y proponer acciones para cuidar y respetar los espacios públicos dentro y fuera de la escuela (como baños, salas de clases, bibliotecas, plazas, parques, playas y calles, entre otros), y reconocer que estos espacios se deben cuidar porque son compartidos por todos.' },
      { codigo: 'OA16', eje: 'Formación Ciudadana',  descripcion: 'Reconocer la importancia y practicar acciones concretas que contribuyan al cuidado y protección del medio ambiente (como apagar luces, cerrar llaves de agua, no arrojar basura, reciclar, reutilizar).' }
    ],
    '3B': [
      { codigo: 'OA1',  eje: 'Historia',             descripcion: 'Describir la vida de las personas en las antiguas civilizaciones (griega y romana), considerando ubicación geográfica, actividades económicas, organización política y social, y aportes culturales al mundo actual (ciencias, artes, arquitectura, leyes, democracia, derecho, entre otros).' },
      { codigo: 'OA2',  eje: 'Historia',             descripcion: 'Identificar las principales zonas climáticas del mundo (polar, templada, tropical, desértica) y dar ejemplos de distintos paisajes que pueden encontrarse en estas zonas y de cómo las personas han elaborado diferentes estrategias para habitarlas.' },
      { codigo: 'OA3',  eje: 'Historia',             descripcion: 'Describir los diversos modos de vida de algunas civilizaciones americanas, como mayas, aztecas e incas, considerando ubicación geográfica, organización política y social, actividades económicas, aportes culturales al mundo actual, y formas de relacionarse con el entorno natural.' },
      { codigo: 'OA4',  eje: 'Historia',             descripcion: 'Localizar, nombrar y ubicar en mapas las principales civilizaciones estudiadas, y comparar sus paisajes y principales características geográficas.' },
      { codigo: 'OA5',  eje: 'Historia',             descripcion: 'Usar herramientas geográficas como mapas, globo terráqueo, planos, fotografías, cartografía digital, entre otros, para identificar elementos del entorno y ubicar lugares de su interés.' },
      { codigo: 'OA6',  eje: 'Geografía',            descripcion: 'Ubicar en mapas las principales civilizaciones de América precolombina (mayas, aztecas e incas) y del mundo antiguo (griega y romana).' },
      { codigo: 'OA7',  eje: 'Geografía',            descripcion: 'Describir la geografía de Chile, considerando climas, relieve, flora y fauna en las distintas zonas del país (norte grande, norte chico, zona central, zona sur y zona austral), y comparar las formas en que las personas viven y se adaptan a ellas.' },
      { codigo: 'OA8',  eje: 'Geografía',            descripcion: 'Identificar en mapas de Chile la ubicación de las grandes ciudades, de la propia región y de las regiones vecinas, reconociendo las capitales regionales y los principales accidentes geográficos.' },
      { codigo: 'OA9',  eje: 'Geografía',            descripcion: 'Distinguir recursos naturales renovables y no renovables, dar ejemplos de ambos y proponer medidas para el uso responsable de los recursos.' },
      { codigo: 'OA10', eje: 'Geografía',            descripcion: 'Reconocer y ubicar en mapas recursos significativos de Chile (como cobre, frutas, productos del mar, vinos, entre otros), explicar sus procesos de exportación y su aporte al país y las regiones.' },
      { codigo: 'OA11', eje: 'Formación Ciudadana',  descripcion: 'Asumir sus deberes en la casa y en la escuela (como cumplir con sus tareas escolares y ayudar en su familia), y dar ejemplos del aporte que estos deberes hacen al bienestar común.' },
      { codigo: 'OA12', eje: 'Formación Ciudadana',  descripcion: 'Reconocer que los niños tienen derechos que les permiten recibir un cuidado especial por parte de la sociedad (a tener una vivienda, alimentación, educación, protección, a expresar opiniones), y dar ejemplos de cómo la sociedad resguarda estos derechos.' },
      { codigo: 'OA13', eje: 'Formación Ciudadana',  descripcion: 'Participar en forma guiada en su comunidad, escuchando las opiniones de los demás, compartiendo actividades con distintos grupos y cumpliendo compromisos que apunten al bienestar común.' },
      { codigo: 'OA14', eje: 'Formación Ciudadana',  descripcion: 'Distinguir algunos actores de la vida social (padres, profesores, alcaldes, autoridades) y reconocer las instituciones que lideran (familia, escuela, municipalidad, gobierno).' },
      { codigo: 'OA15', eje: 'Formación Ciudadana',  descripcion: 'Identificar y explicar, a partir de ejemplos concretos, formas en que se organizan las personas para lograr objetivos comunes, y reconocer el rol de distintos actores que componen una comunidad.' },
      { codigo: 'OA16', eje: 'Formación Ciudadana',  descripcion: 'Participar activamente en conversaciones grupales sobre textos leídos o escuchados en clases o temas de su interés, manteniendo el foco de la conversación, expresando opiniones fundamentadas y respetando los turnos y las opiniones de los demás.' }
    ],
    '4B': [
      { codigo: 'OA1',  eje: 'Historia',             descripcion: 'Explicar los viajes de descubrimiento de Cristóbal Colón, de Hernando de Magallanes y de algún otro explorador, considerando sus objetivos, las rutas recorridas, los avances tecnológicos que facilitaron la navegación, las dificultades y los desafíos que enfrentaron las tripulaciones.' },
      { codigo: 'OA2',  eje: 'Historia',             descripcion: 'Describir el proceso de conquista de América y de Chile, incluyendo a los principales actores (Corona española, colonizadores y conquistadores como Cristóbal Colón, Hernán Cortés, Francisco Pizarro, Diego de Almagro y Pedro de Valdivia), algunas expediciones y conflictos bélicos con los pueblos indígenas y la fundación de ciudades como expresión de la voluntad de permanencia de los españoles en el territorio.' },
      { codigo: 'OA3',  eje: 'Historia',             descripcion: 'Describir algunas dimensiones de la vida colonial en Chile, como organización de la sociedad y grupos sociales, oficios y actividades económicas, costumbres y vida cotidiana, arte y construcciones.' },
      { codigo: 'OA4',  eje: 'Historia',             descripcion: 'Investigar, a partir de distintas fuentes, sobre el proceso de mestizaje y el legado cultural de españoles y pueblos indígenas en la sociedad chilena (como idioma, religión, alimentos, costumbres), reconociendo su importancia para la conformación de la sociedad chilena.' },
      { codigo: 'OA5',  eje: 'Historia',             descripcion: 'Investigar sobre los efectos de la conquista sobre los pueblos indígenas americanos (en lo social, cultural, demográfico) y comparar diferentes visiones sobre este proceso.' },
      { codigo: 'OA6',  eje: 'Geografía',            descripcion: 'Ubicar en mapas las principales rutas de viajes de descubrimiento y de conquista de América y de Chile.' },
      { codigo: 'OA7',  eje: 'Geografía',            descripcion: 'Investigar sobre problemas ambientales (como la escasez de agua, la contaminación de ríos y mares, la deforestación) y proponer soluciones creativas y factibles que favorezcan el cuidado del medio ambiente y el uso responsable de los recursos.' },
      { codigo: 'OA8',  eje: 'Geografía',            descripcion: 'Describir distintos paisajes del continente americano, considerando climas, ríos, población, idiomas, países y grandes ciudades, entre otros, y utilizando vocabulario geográfico adecuado.' },
      { codigo: 'OA9',  eje: 'Geografía',            descripcion: 'Reconocer y ubicar en mapas las grandes zonas geográficas de Chile (norte grande, norte chico, zona central, zona sur y zona austral) y comparar sus características físicas y humanas.' },
      { codigo: 'OA10', eje: 'Geografía',            descripcion: 'Distinguir las principales características de cada una de las grandes zonas de Chile, en cuanto a relieve, clima, flora, fauna, recursos naturales y actividades económicas, utilizando mapas, imágenes y gráficos.' },
      { codigo: 'OA11', eje: 'Formación Ciudadana',  descripcion: 'Explicar en palabras propias lo que son los derechos, reconocer en su entorno situaciones en que estos se respetan o se vulneran, y dar ejemplos de cómo se pueden proteger.' },
      { codigo: 'OA12', eje: 'Formación Ciudadana',  descripcion: 'Explicar y aplicar algunos elementos fundamentales de una sociedad democrática (como la elección de autoridades y representantes), las instituciones que forman parte del Estado (municipios, gobierno regional, poderes Ejecutivo, Legislativo, Judicial) y el rol que cumplen.' },
      { codigo: 'OA13', eje: 'Formación Ciudadana',  descripcion: 'Explicar sus derechos y responsabilidades como niño o niña, destacando la importancia de practicar acciones cotidianas que hagan referencia a ellos (como expresar opiniones, cumplir con sus deberes, cuidar el entorno, respetar a los demás).' },
      { codigo: 'OA14', eje: 'Formación Ciudadana',  descripcion: 'Distinguir algunas instituciones del Estado de Chile, reconocer sus principales funciones y relevancia para la vida de las personas, y describir el rol que cumplen respecto de la participación ciudadana.' },
      { codigo: 'OA15', eje: 'Formación Ciudadana',  descripcion: 'Reconocer, describir y dar ejemplos de sus derechos y responsabilidades como miembros de una comunidad, destacando la importancia del compromiso, la solidaridad, la tolerancia y el respeto en la convivencia cotidiana.' },
      { codigo: 'OA16', eje: 'Formación Ciudadana',  descripcion: 'Participar en forma guiada en su comunidad, mediante iniciativas que consideren proyectos sociales, económicos o culturales que contribuyan al bienestar de la comunidad escolar.' }
    ],
    '5B': [
      { codigo: 'OA1',  eje: 'Historia',             descripcion: 'Explicar los múltiples antecedentes de la independencia de las colonias americanas y reconocer que la independencia de Chile se enmarca en un proceso continental.' },
      { codigo: 'OA2',  eje: 'Historia',             descripcion: 'Explicar el desarrollo del proceso de independencia de Chile, considerando actores y bandos que se enfrentaron, hombres y mujeres destacados, avances y retrocesos de la causa patriota y algunos acontecimientos significativos (Primera Junta Nacional de Gobierno, batallas de Rancagua, Chacabuco y Maipú, declaración de la Independencia).' },
      { codigo: 'OA3',  eje: 'Historia',             descripcion: 'Analizar y comparar las principales características de las Repúblicas conservadora y liberal del siglo XIX, como organización política, principales medidas económicas, sociales, educacionales, entre otras.' },
      { codigo: 'OA4',  eje: 'Historia',             descripcion: 'Describir algunos hitos y procesos de la organización de la República, como las dificultades y los desafíos de la organización política, la Constitución de 1833, las políticas de Diego Portales y el impacto de la guerra contra la Confederación Perú-Boliviana.' },
      { codigo: 'OA5',  eje: 'Historia',             descripcion: 'Describir la sociedad chilena del siglo XIX, considerando temas como la vida cotidiana en la ciudad y el campo, diferencias entre la vida rural y urbana, nuevos medios de transporte y comunicación (como el ferrocarril, telégrafo), influencia de las corrientes europeas en la cultura (como la moda, educación, arquitectura, costumbres).' },
      { codigo: 'OA6',  eje: 'Historia',             descripcion: 'Explicar aspectos centrales de la Guerra del Pacífico, como las causas, actores involucrados, las decisiones estratégicas del Estado, las grandes batallas y el impacto en el país.' },
      { codigo: 'OA7',  eje: 'Historia',             descripcion: 'Explicar la ocupación de la Araucanía, el poblamiento de Valdivia, Llanquihue y Chiloé, y la incorporación de Isla de Pascua, Antofagasta y Tarapacá, reconociendo los intereses del Estado chileno al llevar a cabo estos procesos.' },
      { codigo: 'OA8',  eje: 'Historia',             descripcion: 'Describir algunos hitos y procesos de la historia de Chile durante el siglo XIX, considerando eventos como la ocupación del territorio y el desarrollo de la economía salitrera, la cuestión social, y crisis políticas como la guerra civil de 1891.' },
      { codigo: 'OA9',  eje: 'Geografía',            descripcion: 'Caracterizar las grandes zonas de Chile y sus paisajes (norte grande, norte chico, zona central, zona sur y zona austral) considerando ubicación, clima, relieve, hidrografía, población y recursos naturales, entre otros.' },
      { codigo: 'OA10', eje: 'Geografía',            descripcion: 'Explicar cómo las características físicas de cada una de las grandes zonas de Chile han influido en el asentamiento humano y en los tipos de actividades económicas desarrolladas en cada una de ellas.' },
      { codigo: 'OA11', eje: 'Geografía',            descripcion: 'Reconocer y explicar factores de producción en Chile (como recursos naturales, trabajo, capital y tecnología) y clasificar las actividades económicas según la extracción de recursos naturales (primarias), la transformación de recursos (secundarias) y la prestación de servicios (terciarias).' },
      { codigo: 'OA12', eje: 'Geografía',            descripcion: 'Investigar y explicar diferentes expresiones culturales de Chile, considerando comidas, fiestas, canciones, danzas, poesía y artesanía, entre otras, y valorar su diversidad.' },
      { codigo: 'OA13', eje: 'Formación Ciudadana',  descripcion: 'Reconocer sus principales derechos en situaciones de la vida cotidiana, como el derecho a la educación, a contar con alimentación, vivienda, recreo y servicios médicos adecuados, a expresarse, a ser protegido contra el abandono y la crueldad, y a no trabajar antes de la edad mínima permitida.' },
      { codigo: 'OA14', eje: 'Formación Ciudadana',  descripcion: 'Reconocer que todas las personas son sujetos de derecho, y que estos derechos no dependen de características individuales como etnia, sexo, lugar de nacimiento u otras.' },
      { codigo: 'OA15', eje: 'Formación Ciudadana',  descripcion: 'Caracterizar a Chile como una república democrática y explicar la importancia de que el poder público sea ejercido por autoridades que son elegidas por la ciudadanía.' },
      { codigo: 'OA16', eje: 'Formación Ciudadana',  descripcion: 'Distinguir los tres poderes del Estado, identificando las principales instituciones y autoridades que componen cada uno y sus atribuciones.' }
    ],
    '6B': [
      { codigo: 'OA1',  eje: 'Historia',             descripcion: 'Explicar el desarrollo del proceso de industrialización en Chile desde la segunda mitad del siglo XIX, caracterizando los cambios tecnológicos (como la llegada del ferrocarril, telégrafo), el auge económico del salitre y sus efectos en la economía (aduanas, incentivo al comercio), y los cambios en la sociedad (migración campo-ciudad, aumento poblacional, mejora de servicios urbanos).' },
      { codigo: 'OA2',  eje: 'Historia',             descripcion: 'Describir algunos hitos y procesos relevantes de la historia de Chile del siglo XX (ampliación del sufragio, nuevos derechos civiles y sociales, cambios en la economía, crisis económica de 1929, reformas estructurales de los años 1960 y 1970, quiebre democrático, dictadura, proceso de recuperación de la democracia), sus consecuencias y su proyección hacia nuestros días.' },
      { codigo: 'OA3',  eje: 'Historia',             descripcion: 'Explicar aspectos centrales de la sociedad chilena del siglo XX, como cambios en la familia, en el rol de la mujer, en el sistema educacional, en los medios de comunicación, y las transformaciones de la vida cotidiana.' },
      { codigo: 'OA4',  eje: 'Historia',             descripcion: 'Caracterizar el periodo de la dictadura militar en Chile, considerando la violación a los derechos humanos, la transformación económica, política y social, y el plebiscito de 1988 como la vuelta a la democracia.' },
      { codigo: 'OA5',  eje: 'Historia',             descripcion: 'Describir algunos hitos y procesos de la recuperación de la democracia en Chile desde 1990, tales como los principales cambios políticos y económicos, el rol de los partidos políticos y movimientos sociales, los avances en materia de derechos humanos y la creciente integración del país en el mundo.' },
      { codigo: 'OA6',  eje: 'Geografía',            descripcion: 'Explicar los distintos tipos de recursos naturales (renovables, no renovables e inagotables) y las principales actividades económicas de Chile relacionadas con ellos (agricultura, ganadería, pesca, minería, silvicultura, etc.), identificando los principales recursos que se extraen en las regiones del país.' },
      { codigo: 'OA7',  eje: 'Geografía',            descripcion: 'Describir distintos paisajes de Chile, considerando climas, relieves, vegetación, recursos naturales y actividades humanas, entre otros, y explicar cómo las personas se han adaptado y transformado el medio.' },
      { codigo: 'OA8',  eje: 'Geografía',            descripcion: 'Explicar características de la población de Chile, considerando aspectos demográficos (distribución de la población, composición por sexo y edad, crecimiento poblacional, migración, urbanización) y su impacto en la sociedad.' },
      { codigo: 'OA9',  eje: 'Geografía',            descripcion: 'Caracterizar las grandes zonas de Chile y sus paisajes (norte grande, norte chico, zona central, zona sur y zona austral) considerando su clima, relieve, hidrografía, población y recursos productivos.' },
      { codigo: 'OA10', eje: 'Geografía',            descripcion: 'Explicar y dar ejemplos de las distintas actividades económicas del país, identificando tipos de trabajo, factores productivos, zonas donde se concentran y su importancia para el desarrollo económico y social.' },
      { codigo: 'OA11', eje: 'Formación Ciudadana',  descripcion: 'Explicar algunos elementos fundamentales de la organización democrática de Chile, incluyendo la división de los poderes del Estado, la representación mediante cargos de elección popular (presidente, parlamentarios, alcaldes y concejales), la importancia de la participación ciudadana y el respeto por la diversidad de ideas y creencias.' },
      { codigo: 'OA12', eje: 'Formación Ciudadana',  descripcion: 'Evaluar, considerando aportes de la Constitución de Chile, cómo la libre participación ciudadana, la organización en diversas agrupaciones y el respeto a los derechos humanos, favorecen la vida en comunidad.' },
      { codigo: 'OA13', eje: 'Formación Ciudadana',  descripcion: 'Explicar que los derechos generan deberes y responsabilidades en las personas y en el Estado, lo que se traduce en que los ciudadanos cumplen las leyes, respetan a los demás, contribuyen al país y el Estado garantiza los derechos y provee servicios (como salud, educación, seguridad).' },
      { codigo: 'OA14', eje: 'Formación Ciudadana',  descripcion: 'Reconocer que la Constitución Política de Chile establece la organización política del país y garantiza los derechos y las libertades de las personas, instaurando una república democrática.' },
      { codigo: 'OA15', eje: 'Formación Ciudadana',  descripcion: 'Investigar sobre la discriminación hacia diversos grupos (pueblos indígenas, inmigrantes, mujeres, personas con discapacidad, etc.) en el Chile actual y proponer acciones que contribuyan a combatirla, fomentar la igualdad de derechos y valorar la diversidad.' },
      { codigo: 'OA16', eje: 'Formación Ciudadana',  descripcion: 'Opinar y argumentar con fundamentos sobre temas de la asignatura u otros, y reconocer la importancia del respeto por opiniones distintas a la propia en el debate democrático.' }
    ],
    '7B': [
      { codigo: 'OA1',  eje: 'Historia',             descripcion: 'Explicar el proceso de hominización, reconociendo las principales etapas de la evolución de la especie humana, la influencia de factores geográficos, su dispersión en el planeta y las distintas teorías sobre el poblamiento americano.' },
      { codigo: 'OA2',  eje: 'Historia',             descripcion: 'Explicar que el surgimiento de la agricultura, la domesticación de animales, la sedentarización, la acumulación de bienes y los avances tecnológicos (cerámica, metalurgia, etc.) fueron procesos de larga duración que revolucionaron la forma en que los seres humanos se relacionaron con el espacio geográfico.' },
      { codigo: 'OA3',  eje: 'Historia',             descripcion: 'Explicar las principales características de las primeras civilizaciones (como Mesopotamia, Egipto, China, India) y reconocer su legado en el desarrollo del mundo antiguo y actual.' },
      { codigo: 'OA4',  eje: 'Historia',             descripcion: 'Analizar las principales características de la civilización griega, considerando aspectos como la organización política de las polis, el origen de la democracia, el rol de las mujeres, la esclavitud, la expansión colonial, las guerras y la cultura (filosofía, ciencia, arte y literatura).' },
      { codigo: 'OA5',  eje: 'Historia',             descripcion: 'Analizar las principales características de la civilización romana, considerando el paso de la República al Imperio, la expansión territorial, la organización política y jurídica, la economía, la religión y el legado cultural (derecho romano, idiomas, arquitectura, obras públicas, vida urbana).' },
      { codigo: 'OA6',  eje: 'Historia',             descripcion: 'Analizar, apoyándose en fuentes, el canon cultural que se constituyó en la Antigüedad clásica, considerando los aportes de griegos y romanos a nuestra concepción de la política, el derecho, la ciencia, la filosofía y el arte.' },
      { codigo: 'OA7',  eje: 'Historia',             descripcion: 'Caracterizar el mar Mediterráneo como ecúmene y como espacio de circulación e intercambio, y analizar las formas en que su uso ha perdurado hasta el presente.' },
      { codigo: 'OA8',  eje: 'Historia',             descripcion: 'Analizar el proceso de expansión y caída del Imperio romano de Occidente, considerando el rol de los pueblos germanos, los cambios políticos, económicos y sociales, y el surgimiento de la Europa medieval.' },
      { codigo: 'OA9',  eje: 'Historia',             descripcion: 'Caracterizar la Edad Media como un período en que se configuraron las bases de la civilización europea, considerando el cristianismo, la cultura clásica y la herencia de los pueblos germánicos.' },
      { codigo: 'OA10', eje: 'Historia',             descripcion: 'Explicar los efectos de la caída del Imperio romano y la consecuente ruralización y fragmentación política, considerando el surgimiento del feudalismo como sistema político, económico y social, y las invasiones a Europa (musulmanas, vikingas, magiares).' },
      { codigo: 'OA11', eje: 'Historia',             descripcion: 'Analizar las principales características de la sociedad feudal y el impacto del cristianismo, considerando la fragmentación del poder político, las relaciones de dependencia entre señores y vasallos, y la jerarquía de la Iglesia católica.' },
      { codigo: 'OA12', eje: 'Historia',             descripcion: 'Analizar el desarrollo y el legado de la civilización musulmana, considerando factores geográficos, su expansión, su organización política, su cultura (religión islámica, ciencia, artes) y sus aportes al mundo medieval y actual.' },
      { codigo: 'OA13', eje: 'Historia',             descripcion: 'Caracterizar los principales rasgos del renacimiento de la vida urbana medieval (siglos XI–XIII), como el aumento demográfico, la expansión agrícola, el desarrollo del comercio y la aparición de las ciudades, y evaluar sus consecuencias.' },
      { codigo: 'OA14', eje: 'Geografía',            descripcion: 'Analizar la expansión europea, considerando las motivaciones para explorar y conquistar, los adelantos tecnológicos, la relevancia de los viajes, la redefinición del mapa y del comercio mundial y el impacto en Europa y otras sociedades.' },
      { codigo: 'OA15', eje: 'Geografía',            descripcion: 'Investigar sobre problemas medioambientales relacionados con fenómenos como el calentamiento global, la contaminación y el deterioro de los recursos naturales, y reconocer el impacto de la acción humana en el medio natural.' },
      { codigo: 'OA16', eje: 'Geografía',            descripcion: 'Reconocer procesos de adaptación y transformación que se derivan de la relación entre el ser humano y el medio, e identificar factores que inciden en el asentamiento de las sociedades humanas (disponibilidad de recursos, clima, relieve, vías de comunicación).' },
      { codigo: 'OA17', eje: 'Formación Ciudadana',  descripcion: 'Identificar los principios, mecanismos e instituciones que permitieron que en Atenas surgiera la democracia, y reconocer su legado en las democracias actuales (participación ciudadana, debate público, igualdad ante la ley).' },
      { codigo: 'OA18', eje: 'Formación Ciudadana',  descripcion: 'Analizar cómo los distintos tipos de gobierno (democracia, monarquía, república, imperio, tiranía) enfrentaron desafíos políticos, considerando ejemplos de la Antigüedad clásica y del mundo medieval.' },
      { codigo: 'OA19', eje: 'Formación Ciudadana',  descripcion: 'Reconocer los principales desafíos que enfrenta el ejercicio ciudadano hoy en relación con la protección de los derechos humanos, la exclusión y discriminación, y proponer acciones para contribuir al respeto y valoración de la diversidad.' },
      { codigo: 'OA20', eje: 'Formación Ciudadana',  descripcion: 'Investigar sobre instituciones políticas y procesos históricos que han sido importantes en la construcción de la democracia moderna, y valorar el legado de la Antigüedad y la Edad Media.' }
    ],
    '8B': [
      { codigo: 'OA1',  eje: 'Historia',             descripcion: 'Analizar, apoyándose en diversas fuentes, la centralidad del ser humano y su capacidad de transformar el mundo en las ideas del Renacimiento, considerando sus características principales (humanismo, antropocentrismo, individualismo, curiosidad científica, valoración de la Antigüedad clásica) y su impacto en las artes, las ciencias y la política.' },
      { codigo: 'OA2',  eje: 'Historia',             descripcion: 'Comparar la sociedad medieval y moderna, considerando los cambios que implicó la ruptura de la unidad religiosa de Europa, el surgimiento del Estado moderno, la transformación económica (mercantilismo, capitalismo comercial) y los cambios en la mentalidad y la vida cotidiana.' },
      { codigo: 'OA3',  eje: 'Historia',             descripcion: 'Caracterizar el Estado moderno considerando sus principales rasgos, como la concentración del poder en la figura del rey, la burocracia profesional, la creación de ejércitos permanentes y la unificación territorial, e identificar cómo estas características se expresan en la actualidad.' },
      { codigo: 'OA4',  eje: 'Historia',             descripcion: 'Argumentar por qué la llegada de los europeos a América implicó un enfrentamiento entre culturas, considerando los diversos procesos de dominación y sincretismo cultural, y reconocer el legado presente en la sociedad actual.' },
      { codigo: 'OA5',  eje: 'Historia',             descripcion: 'Analizar el impacto de la conquista de América sobre los pueblos indígenas (violencia, mestizaje, evangelización, reducciones, encomiendas, trabajo forzoso) y valorar sus formas de resistencia y los procesos de mestizaje biológico y cultural que se originaron.' },
      { codigo: 'OA6',  eje: 'Historia',             descripcion: 'Explicar que la conquista española de América y Chile supuso la imposición de la cultura del conquistador y, a la vez, originó una nueva sociedad marcada por el mestizaje y el sincretismo cultural, reconocible hasta el presente.' },
      { codigo: 'OA7',  eje: 'Historia',             descripcion: 'Analizar la organización colonial y las transformaciones del siglo XVIII, considerando las reformas borbónicas, la creación de nuevas instituciones y el impacto económico, social y político en las colonias americanas y en Chile.' },
      { codigo: 'OA8',  eje: 'Historia',             descripcion: 'Caracterizar el orden colonial en Chile, considerando sus principales instituciones políticas (Gobernación, Real Audiencia, Cabildos), el rol de la Iglesia, las relaciones entre grupos sociales, la economía basada en la hacienda y las relaciones con los pueblos indígenas.' },
      { codigo: 'OA9',  eje: 'Historia',             descripcion: 'Explicar las causas y consecuencias de la Ilustración, considerando los principios de razón, libertad, igualdad, progreso, y valorar su influencia en las revoluciones políticas del siglo XVIII (Independencia de Estados Unidos, Revolución Francesa) y en la Independencia de las colonias americanas.' },
      { codigo: 'OA10', eje: 'Historia',             descripcion: 'Analizar los procesos de independencia de las colonias americanas y sus proyectos políticos posteriores, considerando la participación popular, las ideas ilustradas, el rol de los próceres y los desafíos de la organización republicana.' },
      { codigo: 'OA11', eje: 'Historia',             descripcion: 'Explicar el proceso de independencia de Chile, considerando su contexto internacional (influencia de la Ilustración, Revolución Francesa, Independencia de EE.UU.), actores clave, bandos, principales batallas y proyectos políticos que surgieron.' },
      { codigo: 'OA12', eje: 'Historia',             descripcion: 'Caracterizar el proceso de organización de la República de Chile durante las primeras décadas del siglo XIX, identificando los principales actores políticos, los distintos ensayos constitucionales, los conflictos y consensos y la consolidación del orden conservador.' },
      { codigo: 'OA13', eje: 'Geografía',            descripcion: 'Analizar las transformaciones del espacio geográfico europeo y americano entre los siglos XV y XVIII, considerando la expansión territorial, los cambios en el paisaje y el impacto sobre las sociedades originarias.' },
      { codigo: 'OA14', eje: 'Geografía',            descripcion: 'Analizar, a partir de diversas fuentes, las características del proceso de globalización comercial iniciado en el siglo XVI y sus efectos económicos, sociales y culturales en Europa, América y otras partes del mundo.' },
      { codigo: 'OA15', eje: 'Geografía',            descripcion: 'Explicar los distintos tipos de recursos naturales y las principales actividades económicas que se desarrollaron durante los siglos XV al XVIII, y evaluar su impacto social y ambiental.' },
      { codigo: 'OA16', eje: 'Formación Ciudadana',  descripcion: 'Caracterizar los principios y las instituciones de las democracias modernas, considerando la Declaración de los Derechos del Hombre y del Ciudadano (1789), la separación de los poderes del Estado y la universalidad de los derechos humanos.' },
      { codigo: 'OA17', eje: 'Formación Ciudadana',  descripcion: 'Analizar la importancia de los derechos humanos como fundamento de las sociedades democráticas y las consecuencias de su vulneración en la historia reciente, valorando el rol de las instituciones y organismos que velan por ellos.' },
      { codigo: 'OA18', eje: 'Formación Ciudadana',  descripcion: 'Reconocer los principales desafíos que enfrentan las democracias en el mundo actual (participación ciudadana, transparencia, pluralismo, respeto a las minorías, combate a la corrupción) y proponer acciones que contribuyan a fortalecerlas.' },
      { codigo: 'OA19', eje: 'Formación Ciudadana',  descripcion: 'Investigar procesos históricos de ampliación de derechos (como el sufragio universal, la igualdad de género, los derechos de los trabajadores, los derechos de los pueblos indígenas) y analizar su impacto en la conformación de las sociedades democráticas contemporáneas.' },
      { codigo: 'OA20', eje: 'Formación Ciudadana',  descripcion: 'Evaluar el legado histórico y cultural del período estudiado (siglos XV al XVIII) en la formación del mundo moderno, reconociendo continuidades y rupturas en los ámbitos político, económico, social y cultural.' }
    ],
    '1M': [
      { codigo: 'OA1',  eje: 'Historia',             descripcion: 'Explicar las transformaciones sociales, políticas, económicas y culturales que surgen con la crisis del orden liberal a fines del siglo XIX y durante las primeras décadas del siglo XX, considerando el cuestionamiento al parlamentarismo, la emergencia de movimientos obreros y las demandas sociales, el surgimiento de nuevas ideologías, y los cambios en el rol del Estado.' },
      { codigo: 'OA2',  eje: 'Historia',             descripcion: 'Analizar el impacto de la Primera Guerra Mundial, considerando las transformaciones territoriales, políticas, económicas y sociales derivadas de ella, como el surgimiento de nuevos Estados, los tratados de paz, la crisis económica de posguerra y los cambios en las mentalidades.' },
      { codigo: 'OA3',  eje: 'Historia',             descripcion: 'Analizar y evaluar las causas, características y consecuencias del periodo de entreguerras, con foco en la crisis del modelo liberal (Gran Depresión), la emergencia de regímenes totalitarios y la Guerra Civil Española, y reconocer sus efectos en Chile.' },
      { codigo: 'OA4',  eje: 'Historia',             descripcion: 'Analizar los desafíos que enfrentó el Estado y la sociedad chilena durante las primeras décadas del siglo XX (cuestión social, parlamentarismo, proyectos de reforma, rol de los nuevos sectores medios, movimientos obreros y de mujeres) y evaluar los cambios políticos, económicos y sociales que permitieron transformar el país.' },
      { codigo: 'OA5',  eje: 'Historia',             descripcion: 'Caracterizar los principales procesos políticos, económicos y sociales del Chile de mediados del siglo XX, considerando el Estado de compromiso, el proyecto desarrollista (industrialización por sustitución de importaciones), la ampliación de derechos sociales y políticos, y los proyectos de reforma estructural.' },
      { codigo: 'OA6',  eje: 'Historia',             descripcion: 'Analizar la Segunda Guerra Mundial, considerando sus causas y características (totalitarismo, genocidio, bombardeos atómicos), sus consecuencias a nivel mundial (surgimiento de EE.UU. y la URSS como superpotencias, creación de la ONU, descolonización) y el impacto en Chile y América Latina.' },
      { codigo: 'OA7',  eje: 'Historia',             descripcion: 'Caracterizar la Guerra Fría como un enfrentamiento ideológico, político y económico entre EE.UU. y la URSS, considerando sus principales crisis (Muro de Berlín, Cuba, Vietnam), la carrera armamentista y espacial, y su impacto en América Latina (intervencionismo, Revolución Cubana, doctrinas de seguridad nacional).' },
      { codigo: 'OA8',  eje: 'Historia',             descripcion: 'Analizar los procesos de cambio y polarización política en Chile entre 1958 y 1973, considerando los proyectos de reforma (Alessandri, Frei Montalva, Allende), la Reforma Agraria, la nacionalización del cobre, las transformaciones sociales y la crisis democrática que desembocó en el quiebre institucional de 1973.' },
      { codigo: 'OA9',  eje: 'Geografía',            descripcion: 'Analizar las transformaciones del espacio geográfico chileno y latinoamericano durante el siglo XX, considerando la urbanización, la industrialización, los procesos migratorios campo-ciudad y las transformaciones del paisaje rural y urbano.' },
      { codigo: 'OA10', eje: 'Geografía',            descripcion: 'Analizar la globalización como un proceso geográfico, económico y cultural que ha transformado el mundo desde la segunda mitad del siglo XX, considerando el desarrollo de las comunicaciones, la interdependencia económica, los flujos migratorios y la hibridación cultural.' },
      { codigo: 'OA11', eje: 'Geografía',            descripcion: 'Analizar cómo las actividades humanas han transformado el territorio, generando problemáticas ambientales (deforestación, contaminación, pérdida de biodiversidad) y evaluando su impacto en el desarrollo sostenible.' },
      { codigo: 'OA12', eje: 'Formación Ciudadana',  descripcion: 'Analizar el concepto de Estado de derecho, reconociendo los principios de legalidad, separación de poderes, responsabilidad de los gobernantes, respeto a los derechos humanos y control ciudadano, como pilares de una sociedad democrática.' },
      { codigo: 'OA13', eje: 'Formación Ciudadana',  descripcion: 'Evaluar el impacto de la violación sistemática a los derechos humanos durante el período de la dictadura militar en Chile (1973–1990), considerando los mecanismos represivos, las formas de resistencia, y el rol de los organismos nacionales e internacionales en la defensa de los derechos humanos.' },
      { codigo: 'OA14', eje: 'Formación Ciudadana',  descripcion: 'Analizar la recuperación de la democracia en Chile desde 1990, considerando los desafíos de la transición, los avances en materia de derechos humanos, las transformaciones políticas, económicas y sociales, y los pendientes de la democracia actual.' },
      { codigo: 'OA15', eje: 'Formación Ciudadana',  descripcion: 'Reconocer la importancia de la participación ciudadana y el respeto a la diversidad en la construcción de una sociedad democrática, y proponer formas de compromiso con los desafíos del país y del mundo actual.' }
    ],
    '2M': [
      { codigo: 'OA1',  eje: 'Historia',             descripcion: 'Analizar las transformaciones de la sociedad y la cultura contemporánea, considerando los procesos de secularización, el desarrollo científico y tecnológico, los cambios en la familia y en los roles de género, y la emergencia de nuevas subjetividades y movimientos culturales desde mediados del siglo XX.' },
      { codigo: 'OA2',  eje: 'Historia',             descripcion: 'Analizar el fin de la Guerra Fría, considerando la caída del Muro de Berlín, la disolución de la URSS, y sus consecuencias geopolíticas, económicas y culturales en el mundo y en Chile, incluyendo la consolidación de un mundo unipolar y la posterior emergencia de nuevos actores internacionales.' },
      { codigo: 'OA3',  eje: 'Historia',             descripcion: 'Analizar los procesos de integración regional y subregional en América Latina (Mercosur, Comunidad Andina, Alianza del Pacífico) y sus desafíos, considerando las dimensiones económicas, políticas y culturales, y evaluar su aporte al desarrollo de Chile.' },
      { codigo: 'OA4',  eje: 'Historia',             descripcion: 'Reconocer los principales hitos del proceso de democratización del Estado chileno durante el siglo XX, considerando la ampliación del sufragio, la incorporación de la mujer a la política, el reconocimiento de los derechos de los pueblos originarios, los derechos sociales y los desafíos pendientes.' },
      { codigo: 'OA5',  eje: 'Geografía',            descripcion: 'Caracterizar el territorio nacional como un espacio diverso y dinámico, analizando las grandes macrozonas de Chile (norte, centro, sur, austral, insular), sus paisajes, poblamiento, actividades económicas y cómo se han transformado por la acción humana y los procesos globales.' },
      { codigo: 'OA6',  eje: 'Geografía',            descripcion: 'Analizar el rol de los recursos naturales en la economía nacional y en las economías regionales, considerando la matriz productiva de Chile, los procesos de extracción, transformación y exportación, y los desafíos de la sustentabilidad y la diversificación productiva.' },
      { codigo: 'OA7',  eje: 'Geografía',            descripcion: 'Analizar los desafíos demográficos actuales en Chile y el mundo (envejecimiento poblacional, transición demográfica, migraciones internacionales, urbanización, concentración metropolitana) y su impacto en las políticas públicas y en la calidad de vida.' },
      { codigo: 'OA8',  eje: 'Geografía',            descripcion: 'Evaluar los impactos ambientales del desarrollo económico contemporáneo en Chile y en el mundo (cambio climático, pérdida de biodiversidad, contaminación, escasez hídrica) y analizar iniciativas locales, regionales y globales orientadas al desarrollo sostenible.' },
      { codigo: 'OA9',  eje: 'Geografía',            descripcion: 'Caracterizar la globalización como un proceso multidimensional (económico, político, cultural, tecnológico) que ha reconfigurado las relaciones entre los países y los territorios, y evaluar sus impactos en la sociedad chilena.' },
      { codigo: 'OA10', eje: 'Economía',             descripcion: 'Analizar el funcionamiento básico del sistema económico (mercado, oferta y demanda, rol del Estado, sistema monetario, indicadores económicos como PIB, IPC, desempleo) y evaluar cómo las políticas económicas afectan la vida cotidiana de las personas.' },
      { codigo: 'OA11', eje: 'Economía',             descripcion: 'Evaluar las transformaciones del mercado del trabajo contemporáneo en Chile y en el mundo, considerando la flexibilización laboral, la automatización, la precarización, los derechos laborales y los desafíos para la inclusión y equidad.' },
      { codigo: 'OA12', eje: 'Formación Ciudadana',  descripcion: 'Analizar los mecanismos e instituciones de la democracia representativa en Chile (sistema electoral, partidos políticos, Congreso, poder Ejecutivo, poder Judicial, órganos autónomos) y evaluar su funcionamiento, sus desafíos y los mecanismos de participación ciudadana vigentes.' },
      { codigo: 'OA13', eje: 'Formación Ciudadana',  descripcion: 'Evaluar el rol del Estado en la garantía de los derechos humanos, considerando los derechos civiles, políticos, económicos, sociales y culturales, y analizar los desafíos de Chile en materia de derechos humanos, especialmente respecto de pueblos originarios, mujeres, niños, migrantes y personas con discapacidad.' },
      { codigo: 'OA14', eje: 'Formación Ciudadana',  descripcion: 'Reconocer el valor de la participación ciudadana en la democracia, considerando los mecanismos institucionales (plebiscitos, elecciones, consultas) y no institucionales (movimientos sociales, medios de comunicación, redes sociales) y proponer formas de participación informada y responsable.' },
      { codigo: 'OA15', eje: 'Formación Ciudadana',  descripcion: 'Analizar el concepto de ciudadanía global en un contexto de interdependencia mundial, considerando los desafíos comunes a la humanidad (paz, derechos humanos, medio ambiente, desarrollo sostenible, cooperación internacional) y el rol de Chile en organismos internacionales.' }
    ]
  }
};

// =============================================================================
//  ELECTIVOS DE FORMACIÓN GENERAL — 3° y 4° medio
//  Fuente: Bases Curriculares 3°–4° medio (DS 193/2019).
//  OAs idénticos para 3°M y 4°M según Programa de Estudio Mineduc 2021.
// =============================================================================

(function buildOasCLA() {
  var OAS_CLA = [
    { codigo:'OA1', eje:'Conocimiento y comprensión', descripcion:'Analizar procesos sociales y culturales recientes de Chile y América Latina tales como migraciones, cambios demográficos y urbanización, considerando avances y desafíos comunes en materia de equidad, diversidad e interculturalidad.' },
    { codigo:'OA2', eje:'Conocimiento y comprensión', descripcion:'Explicar procesos comunes de los Estados latinoamericanos en la historia política reciente, incluyendo la relación entre el poder civil y las fuerzas armadas, transiciones, la defensa y promoción de los derechos humanos y el fortalecimiento de las democracias.' },
    { codigo:'OA3', eje:'Conocimiento y comprensión', descripcion:'Investigar cómo en América Latina los Estados responden a desafíos económicos y sociales, como pobreza, desigualdad, crecimiento económico, desarrollo social y diversificación de la matriz productiva, aplicando conceptos de la economía e información de fuentes e indicadores económicos (PIB, distribución del ingreso, empleo y producción, entre otros).' },
    { codigo:'OA4', eje:'Conocimiento y comprensión', descripcion:'Analizar, a partir de distintas interpretaciones y perspectivas, el presente de distintos pueblos indígenas de Chile y Latinoamérica, considerando su cultura, los procesos históricos recientes y los avances y desafíos en su relación con los Estados nacionales de la región.' },
    { codigo:'OA5', eje:'Conocimiento y comprensión', descripcion:'Evaluar, a partir de la investigación, el estado del medioambiente en Chile y América Latina, incluyendo efectos de distintas actividades humanas y acciones emprendidas por los Estados de la región para avanzar en sustentabilidad.' },
    { codigo:'OA6', eje:'Conocimiento y comprensión', descripcion:'Analizar las oportunidades que ofrecen a los Estados de América Latina la integración y la cooperación internacional, examinando la conformación de bloques económicos y los tratados y acuerdos en materia de economía, derechos humanos, educación, género, salud y ciencia.' },
    { codigo:'OA7', eje:'Conocimiento y comprensión', descripcion:'Participar en forma colaborativa en el diseño de propuestas para dar solución a problemas presentes a nivel local relacionadas con temas abordados en el nivel.' },
    { codigo:'OAa', eje:'Habilidades — Investigación', descripcion:'Investigar sobre la realidad considerando: formulación de preguntas o problemas de investigación a partir de la observación de fenómenos; levantamiento de información a partir de métodos y técnicas propias de historia, geografía, economía y otras ciencias sociales; análisis crítico de las evidencias y evaluación de su validez, considerando su uso ético para respaldar opiniones; definición del marco teórico, del estado de la cuestión y de los conceptos disciplinares del tema a investigar; análisis de las propias conclusiones en relación con los supuestos iniciales.' },
    { codigo:'OAb', eje:'Habilidades — Pensamiento crítico', descripcion:'Hacer conexiones entre fenómenos, acontecimientos y/o procesos de la realidad considerando conceptos como multidimensionalidad, multicausalidad y multiescalaridad, temporalidad, y variables y patrones.' },
    { codigo:'OAc', eje:'Habilidades — Pensamiento crítico', descripcion:'Elaborar interpretaciones y argumentos, basados en fuentes variadas y pertinentes, haciendo uso ético de la información.' },
    { codigo:'OAd', eje:'Habilidades — Pensamiento crítico', descripcion:'Analizar interpretaciones y perspectivas de diversas fuentes, considerando propósito, intencionalidad, enfoque y contexto del autor, y las preguntas que intenta responder.' },
    { codigo:'OAe', eje:'Habilidades — Pensamiento crítico', descripcion:'Evaluar la validez de las propias interpretaciones sobre acontecimientos, fenómenos y procesos estudiados, a través del diálogo y el uso de fuentes.' },
    { codigo:'OAf', eje:'Habilidades — Pensamiento crítico', descripcion:'Elaborar juicios éticos de manera rigurosa y basados en conocimiento disciplinar sobre hitos, fenómenos, procesos, ideas, acciones de personas, entre otros.' },
    { codigo:'OAg', eje:'Habilidades — Comunicación', descripcion:'Comunicar explicaciones, conclusiones u opiniones fundamentadas haciendo uso de lenguaje, las normas y convenciones de la disciplina.' }
  ];
  CURRICULA_PLAN_COMUN['chile-latam'] = {
    nombre: 'Chile y la región latinoamericana',
    sigla:  'CLA',
    tramo:  'media',
    niveles: ['3M','4M'],
    unidades: {
      '3M': ['Procesos políticos recientes en América Latina','Pueblos indígenas y diversidad cultural','Desafíos económicos y sociales','Integración y cooperación regional'],
      '4M': ['Procesos políticos recientes en América Latina','Pueblos indígenas y diversidad cultural','Desafíos económicos y sociales','Integración y cooperación regional']
    },
    oas: { '3M': OAS_CLA, '4M': OAS_CLA },
    actitudes: [
      'Trabajar con responsabilidad y liderazgo en la realización de las tareas colaborativas y en función del logro de metas comunes.',
      'Participar asumiendo posturas razonadas en distintos ámbitos: cultural, social, político y medioambiental, entre otros.',
      'Actuar de acuerdo con los principios de la ética en el uso de la información y de la tecnología, respetando la propiedad intelectual y la privacidad de las personas.',
      'Pensar con flexibilidad para reelaborar las propias ideas, puntos de vista y creencias.',
      'Trabajar colaborativamente en la generación, desarrollo y gestión de proyectos y la resolución de problemas, integrando las diferentes ideas y puntos de vista.',
      'Trabajar con empatía y respeto en el contexto de la diversidad, eliminando toda expresión de prejuicio y discriminación.'
    ]
  };
})();

(function buildOasMUG() {
  var OAS_MUG = [
    { codigo:'OA1', eje:'Conocimiento y comprensión', descripcion:'Analizar procesos migratorios contemporáneos en distintas regiones del mundo considerando múltiples causas, principales características, impactos en la sociedad de origen y de destino, y los desafíos para las sociedades y los Estados nacionales.' },
    { codigo:'OA2', eje:'Conocimiento y comprensión', descripcion:'Investigar algunos aspectos de la economía global actual como cambios en la producción y en el mercado del trabajo, el rol del comercio mundial y del mercado financiero, y nuevas formas de consumo, aplicando conceptos de la economía (escasez, oferta y demanda, precio, balanza comercial, entre otros).' },
    { codigo:'OA3', eje:'Conocimiento y comprensión', descripcion:'Explicar el cambio climático como fenómeno global, incluyendo controversias sobre sus múltiples causas, los grados de responsabilidad de distintos actores y sus principales consecuencias para la población.' },
    { codigo:'OA4', eje:'Conocimiento y comprensión', descripcion:'Analizar, por medio de la investigación, desastres socionaturales, considerando amenazas naturales, el papel de la sociedad y el Estado en la prevención y gestión del riesgo, factores que inciden en la vulnerabilidad de la población y avances de Chile y otros países en la materia.' },
    { codigo:'OA5', eje:'Conocimiento y comprensión', descripcion:'Explicar, por medio de la investigación, transformaciones del Estado-nación en la actualidad, en relación con aspectos como la ciudadanía en un mundo cada vez más interconectado, la internacionalización de la economía y la relación con otros Estados y organismos intergubernamentales.' },
    { codigo:'OA6', eje:'Conocimiento y comprensión', descripcion:'Analizar algunos conflictos internacionales que involucran a Estados nacionales, sociedades o grupos, explicando sus contextos, posibilidades de resolución y aplicando conceptos de la ciencia política como poder, soberanía, ideología, derechos humanos, opinión pública, entre otros.' },
    { codigo:'OA7', eje:'Conocimiento y comprensión', descripcion:'Participar en forma colaborativa en el diseño de propuestas para dar solución a problemas presentes a nivel local relacionadas con temas abordados en el nivel.' },
    { codigo:'OAa', eje:'Habilidades — Investigación', descripcion:'Investigar sobre la realidad considerando: formulación de preguntas o problemas de investigación a partir de la observación de fenómenos; levantamiento de información a partir de métodos y técnicas propias de historia, geografía, economía y otras ciencias sociales; análisis crítico de las evidencias y evaluación de su validez, considerando su uso ético para respaldar opiniones; definición del marco teórico, del estado de la cuestión y de los conceptos disciplinares del tema a investigar; análisis de las propias conclusiones en relación con los supuestos iniciales.' },
    { codigo:'OAb', eje:'Habilidades — Pensamiento crítico', descripcion:'Hacer conexiones entre fenómenos, acontecimientos y/o procesos de la realidad considerando conceptos como multidimensionalidad, multicausalidad y multiescalaridad, temporalidad, y variables y patrones.' },
    { codigo:'OAc', eje:'Habilidades — Pensamiento crítico', descripcion:'Elaborar interpretaciones y argumentos, basados en fuentes variadas y pertinentes, haciendo uso ético de la información.' },
    { codigo:'OAd', eje:'Habilidades — Pensamiento crítico', descripcion:'Analizar interpretaciones y perspectivas de diversas fuentes, considerando propósito, intencionalidad, enfoque y contexto del autor, y las preguntas que intenta responder.' },
    { codigo:'OAe', eje:'Habilidades — Pensamiento crítico', descripcion:'Evaluar la validez de las propias interpretaciones sobre acontecimientos, fenómenos y procesos estudiados, a través del diálogo y el uso de fuentes.' },
    { codigo:'OAf', eje:'Habilidades — Pensamiento crítico', descripcion:'Elaborar juicios éticos de manera rigurosa y basados en conocimiento disciplinar sobre hitos, fenómenos, procesos, ideas, acciones de personas, entre otros.' },
    { codigo:'OAg', eje:'Habilidades — Comunicación', descripcion:'Comunicar explicaciones, conclusiones u opiniones fundamentadas haciendo uso de lenguaje, las normas y convenciones de la disciplina.' }
  ];
  CURRICULA_PLAN_COMUN['mundo-global'] = {
    nombre: 'Comprensión histórica del presente (Mundo global)',
    sigla:  'MUG',
    tramo:  'media',
    niveles: ['3M','4M'],
    unidades: {
      '3M': ['Procesos migratorios y Estado-nación','Conflictos internacionales y economía global','Cambio climático y desastres socionaturales','Ciudadanía global y propuestas locales'],
      '4M': ['Procesos migratorios y Estado-nación','Conflictos internacionales y economía global','Cambio climático y desastres socionaturales','Ciudadanía global y propuestas locales']
    },
    oas: { '3M': OAS_MUG, '4M': OAS_MUG },
    actitudes: [
      'Pensar con flexibilidad para reelaborar las propias ideas, puntos de vista y creencias.',
      'Trabajar colaborativamente en la generación, desarrollo y gestión de proyectos y la resolución de problemas, integrando las diferentes ideas y puntos de vista.',
      'Trabajar con empatía y respeto en el contexto de la diversidad, eliminando toda expresión de prejuicio y discriminación.',
      'Participar asumiendo posturas razonadas en distintos ámbitos: cultural, social, político, medioambiental, entre otros.',
      'Trabajar con responsabilidad y liderazgo en la realización de las tareas colaborativas y en función del logro de metas comunes.',
      'Actuar de acuerdo con los principios de la ética en el uso de la información y de la tecnología, respetando la propiedad intelectual y la privacidad de las personas.'
    ]
  };
})();


(function buildOasGTS() {
  var OAS_GTS = [
    { codigo:'OA1', eje:'Conocimiento y comprensión', descripcion:'Analizar críticamente las dinámicas que se producen entre la población y los recursos en el territorio, considerando demanda, escasez, conflicto y sostenibilidad, a distintas escalas geográficas (local, regional, global).' },
    { codigo:'OA2', eje:'Conocimiento y comprensión', descripcion:'Explicar la conformación de paisajes y territorios a partir de la interacción de factores físico-naturales y humanos, comprendiendo conceptos como geografía física, regionalización y representación geográfica, e integrando herramientas como SIG y cartografía.' },
    { codigo:'OA3', eje:'Conocimiento y comprensión', descripcion:'Evaluar los problemas socioambientales actuales (cambio climático, contaminación, pérdida de biodiversidad, gestión del agua y residuos), incluyendo sus dimensiones políticas, económicas y éticas, así como acciones individuales y colectivas que pueden contribuir a su solución.' },
    { codigo:'OA4', eje:'Conocimiento y comprensión', descripcion:'Analizar amenazas y desastres socionaturales en el territorio considerando las vulnerabilidades de la población, los mecanismos institucionales de prevención y gestión del riesgo y el rol de la ciudadanía organizada.' },
    { codigo:'OA5', eje:'Conocimiento y comprensión', descripcion:'Explicar dinámicas demográficas, migratorias y urbanas en distintas escalas, considerando movilidad, crecimiento de las ciudades, exclusión social, derecho a la ciudad y políticas de planificación territorial.' },
    { codigo:'OA6', eje:'Conocimiento y comprensión', descripcion:'Investigar conflictos territoriales contemporáneos en Chile y otras regiones del mundo (uso del suelo, pueblos originarios, fronteras, recursos naturales), identificando actores, intereses, dimensiones éticas y propuestas de solución.' },
    { codigo:'OA7', eje:'Conocimiento y comprensión', descripcion:'Participar en forma colaborativa en el diseño de propuestas para abordar problemas socioambientales presentes en su entorno local, integrando enfoques de sostenibilidad y de derechos humanos.' },
    { codigo:'OAa', eje:'Habilidades — Investigación', descripcion:'Investigar sobre la realidad considerando: formulación de preguntas o problemas de investigación a partir de la observación de fenómenos; levantamiento de información a partir de métodos y técnicas propias de historia, geografía, economía y otras ciencias sociales; análisis crítico de las evidencias y evaluación de su validez, considerando su uso ético para respaldar opiniones; definición del marco teórico, del estado de la cuestión y de los conceptos disciplinares del tema a investigar; análisis de las propias conclusiones en relación con los supuestos iniciales.' },
    { codigo:'OAb', eje:'Habilidades — Pensamiento crítico', descripcion:'Hacer conexiones entre fenómenos, acontecimientos y/o procesos de la realidad considerando conceptos como multidimensionalidad, multicausalidad y multiescalaridad, temporalidad, y variables y patrones.' },
    { codigo:'OAc', eje:'Habilidades — Pensamiento crítico', descripcion:'Elaborar interpretaciones y argumentos, basados en fuentes variadas y pertinentes, haciendo uso ético de la información.' },
    { codigo:'OAd', eje:'Habilidades — Pensamiento crítico', descripcion:'Analizar interpretaciones y perspectivas de diversas fuentes, considerando propósito, intencionalidad, enfoque y contexto del autor, y las preguntas que intenta responder.' },
    { codigo:'OAe', eje:'Habilidades — Pensamiento crítico', descripcion:'Evaluar la validez de las propias interpretaciones sobre acontecimientos, fenómenos y procesos estudiados, a través del diálogo y el uso de fuentes.' },
    { codigo:'OAf', eje:'Habilidades — Pensamiento crítico', descripcion:'Elaborar juicios éticos de manera rigurosa y basados en conocimiento disciplinar sobre hitos, fenómenos, procesos, ideas, acciones de personas, entre otros.' },
    { codigo:'OAg', eje:'Habilidades — Comunicación', descripcion:'Comunicar explicaciones, conclusiones u opiniones fundamentadas haciendo uso de lenguaje, las normas y convenciones de la disciplina.' }
  ];
  CURRICULA_PLAN_COMUN['geografia-territorio'] = {
    nombre: 'Geografía, Territorio y Desafíos Socioambientales',
    sigla:  'GTS',
    tramo:  'media',
    niveles: ['3M','4M'],
    unidades: {
      '3M': ['Población, recursos y sostenibilidad','Paisajes y representaciones del territorio','Problemas socioambientales y cambio climático','Conflictos territoriales y propuestas locales'],
      '4M': ['Población, recursos y sostenibilidad','Paisajes y representaciones del territorio','Problemas socioambientales y cambio climático','Conflictos territoriales y propuestas locales']
    },
    oas: { '3M': OAS_GTS, '4M': OAS_GTS },
    actitudes: [
      'Trabajar con responsabilidad y liderazgo en la realización de las tareas colaborativas y en función del logro de metas comunes.',
      'Pensar con flexibilidad para reelaborar las propias ideas, puntos de vista y creencias.',
      'Trabajar con empatía y respeto en el contexto de la diversidad, eliminando toda expresión de prejuicio y discriminación.',
      'Participar asumiendo posturas razonadas en distintos ámbitos: cultural, social, político, medioambiental, entre otros.',
      'Actuar de acuerdo con los principios de la ética en el uso de la información y de la tecnología, respetando la propiedad intelectual y la privacidad de las personas.'
    ]
  };
})();

(function buildOasECS() {
  var OAS_ECS = [
    { codigo:'OA1', eje:'Conocimiento y comprensión', descripcion:'Analizar problemas económicos contemporáneos (escasez, desigualdad, desempleo, inflación) considerando sus impactos en la calidad de vida de las personas y aplicando conceptos como oferta y demanda, precio, mercado, política fiscal y monetaria.' },
    { codigo:'OA2', eje:'Conocimiento y comprensión', descripcion:'Investigar la organización del trabajo en la sociedad actual, considerando transformaciones tecnológicas, flexibilidad laboral, brechas de género y derechos laborales, evaluando sus efectos sobre la cohesión social.' },
    { codigo:'OA3', eje:'Conocimiento y comprensión', descripcion:'Explicar el rol del Estado y del mercado en la economía, contrastando distintas perspectivas teóricas (liberal, keynesiana, social de mercado) y analizando las funciones de las políticas públicas en bienestar, regulación y redistribución.' },
    { codigo:'OA4', eje:'Conocimiento y comprensión', descripcion:'Evaluar el impacto del comercio internacional, los tratados, la integración regional y la globalización en la economía y la sociedad chilenas, considerando oportunidades y riesgos.' },
    { codigo:'OA5', eje:'Conocimiento y comprensión', descripcion:'Analizar la economía personal y familiar, integrando conceptos de presupuesto, ahorro, crédito y endeudamiento, y comprendiendo el sistema financiero y de protección al consumidor.' },
    { codigo:'OA6', eje:'Conocimiento y comprensión', descripcion:'Investigar las dimensiones éticas de la actividad económica (sostenibilidad, responsabilidad social, economía circular, economía solidaria), contrastando casos y perspectivas presentes en Chile y otras regiones del mundo.' },
    { codigo:'OA7', eje:'Conocimiento y comprensión', descripcion:'Participar en forma colaborativa en el diseño de propuestas para abordar problemas económicos y sociales presentes en su entorno local, integrando criterios de bien común y justicia social.' },
    { codigo:'OAa', eje:'Habilidades — Investigación', descripcion:'Investigar sobre la realidad considerando: formulación de preguntas o problemas de investigación a partir de la observación de fenómenos; levantamiento de información a partir de métodos y técnicas propias de historia, geografía, economía y otras ciencias sociales; análisis crítico de las evidencias y evaluación de su validez, considerando su uso ético para respaldar opiniones; definición del marco teórico, del estado de la cuestión y de los conceptos disciplinares del tema a investigar; análisis de las propias conclusiones en relación con los supuestos iniciales.' },
    { codigo:'OAb', eje:'Habilidades — Pensamiento crítico', descripcion:'Hacer conexiones entre fenómenos, acontecimientos y/o procesos de la realidad considerando conceptos como multidimensionalidad, multicausalidad y multiescalaridad, temporalidad, y variables y patrones.' },
    { codigo:'OAc', eje:'Habilidades — Pensamiento crítico', descripcion:'Elaborar interpretaciones y argumentos, basados en fuentes variadas y pertinentes, haciendo uso ético de la información.' },
    { codigo:'OAd', eje:'Habilidades — Pensamiento crítico', descripcion:'Analizar interpretaciones y perspectivas de diversas fuentes, considerando propósito, intencionalidad, enfoque y contexto del autor, y las preguntas que intenta responder.' },
    { codigo:'OAe', eje:'Habilidades — Pensamiento crítico', descripcion:'Evaluar la validez de las propias interpretaciones sobre acontecimientos, fenómenos y procesos estudiados, a través del diálogo y el uso de fuentes.' },
    { codigo:'OAf', eje:'Habilidades — Pensamiento crítico', descripcion:'Elaborar juicios éticos de manera rigurosa y basados en conocimiento disciplinar sobre hitos, fenómenos, procesos, ideas, acciones de personas, entre otros.' },
    { codigo:'OAg', eje:'Habilidades — Comunicación', descripcion:'Comunicar explicaciones, conclusiones u opiniones fundamentadas haciendo uso de lenguaje, las normas y convenciones de la disciplina.' }
  ];
  CURRICULA_PLAN_COMUN['economia-sociedad'] = {
    nombre: 'Economía y Sociedad',
    sigla:  'ECS',
    tramo:  'media',
    niveles: ['3M','4M'],
    unidades: {
      '3M': ['Problemas económicos y desigualdad','Trabajo, tecnología y derechos','Estado, mercado y políticas públicas','Globalización, ética y economía personal'],
      '4M': ['Problemas económicos y desigualdad','Trabajo, tecnología y derechos','Estado, mercado y políticas públicas','Globalización, ética y economía personal']
    },
    oas: { '3M': OAS_ECS, '4M': OAS_ECS },
    actitudes: [
      'Trabajar con responsabilidad y liderazgo en la realización de las tareas colaborativas y en función del logro de metas comunes.',
      'Pensar con flexibilidad para reelaborar las propias ideas, puntos de vista y creencias.',
      'Trabajar con empatía y respeto en el contexto de la diversidad, eliminando toda expresión de prejuicio y discriminación.',
      'Participar asumiendo posturas razonadas en distintos ámbitos: cultural, social, político, medioambiental, entre otros.',
      'Actuar de acuerdo con los principios de la ética en el uso de la información y de la tecnología, respetando la propiedad intelectual y la privacidad de las personas.'
    ]
  };
})();
